import { describe, expect, it } from 'vitest'
import type { LegacyShowPackMigrationWorksheet } from './legacy-show-pack-audit'
import type { LegacyShowPackAuthoringWorksheet } from './legacy-show-pack-authoring'
import { applyLegacySignatureFamilyDecisions, type LegacySignatureFamilyDecisionManifest } from './legacy-signature-family-authoring'

const SHA = 'a'.repeat(64)
function legacy(): LegacyShowPackMigrationWorksheet { return { catalog: { signature_beats: [{ id: 1, trigger_text: 'A kills on screen.', entity_id: 'a' }, { id: 2, trigger_text: 'A clashes on screen.', entity_id: 'a' }, { id: 3, trigger_text: 'Other.', entity_id: 'a' }] } } as unknown as LegacyShowPackMigrationWorksheet }
function authoring(): LegacyShowPackAuthoringWorksheet { return { source: { worksheet_sha256: SHA }, pack_draft: { id: 'pack', version: 1 }, claims: [{ id: 'a-state', canon: 'screen', status: 'verified' }], entities: [{ legacy_entity_id: 'a', dossier: { fact_claim_ids: ['a-state'] } }], signature_beats: [1,2,3].map(id=>({ legacy_signature_beat_id:id, contract:null })) } as unknown as LegacyShowPackAuthoringWorksheet }
function manifest(): LegacySignatureFamilyDecisionManifest { return { manifest_version:1, artifact:'legacy-signature-family-decisions', batch_id:'families', target:{pack_id:'pack',pack_version:1}, legacy_worksheet_sha256:SHA, families:[{ family_id:'kills', beat_ids:[1], conditions_by_beat_id:{'1':'A kills on screen.'}, exclusions:['Orders and off-screen kills do not count.'], adjudication:{proxies:'do_not_count',offscreen:'do_not_count',mentions:'do_not_count'}, title_review_note:'Kills requires a direct on-screen kill.' },{ family_id:'clashes',beat_ids:[2],conditions_by_beat_id:{'2':'A clashes on screen.'},exclusions:['Indirect disagreement does not count.'],adjudication:{proxies:'do_not_count',offscreen:'do_not_count',mentions:'do_not_count'},title_review_note:'Clashes requires a direct on-screen confrontation.' }] } }

describe('legacy signature family authoring',()=>{
  it('applies explicit family IDs with owner grounding and leaves other beats open',()=>{const r=applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:manifest()});expect(r.applied_beat_ids).toEqual([1,2]);expect(r.worksheet.signature_beats[0].contract).toMatchObject({condition:'A kills on screen.',basis_claim_ids:['a-state'],title_review:{status:'approved'}});expect(r.worksheet.signature_beats[2].contract).toBeNull()})
  it('requires exact per-ID audited text and no repeated IDs',()=>{const changed=manifest();changed.families[0].conditions_by_beat_id['1']='Different.';expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:changed})).toThrow('signature beat 1 condition must match the audited trigger text');const repeated=manifest();repeated.families[1].beat_ids=[1];repeated.families[1].conditions_by_beat_id={'1':'A kills on screen.'};expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:repeated})).toThrow('signature family beat ids must not contain duplicates')})
  it('rejects condition-map keys outside the explicit family IDs',()=>{const extra=manifest();extra.families[0].conditions_by_beat_id['3']='Other.';expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:extra})).toThrow('signature family kills conditions must exactly cover its beat ids')})
  it('supports exact per-beat relational grounding and requires the owner',()=>{const related=manifest();related.families[0].basis_legacy_entity_ids_by_beat_id={'1':['a']};const result=applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:related});expect(result.worksheet.signature_beats[0].contract?.basis_claim_ids).toEqual(['a-state']);related.families[0].basis_legacy_entity_ids_by_beat_id={'1':[]};expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:related})).toThrow('signature beat 1 basis must include its audited owner')})
  it('rejects duplicate family identities and duplicate exclusions',()=>{const duplicate=manifest();duplicate.families[1].family_id='kills';expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:duplicate})).toThrow('signature family ids must not contain duplicates');const exclusion=manifest();exclusion.families[0].exclusions.push(exclusion.families[0].exclusions[0]);expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:exclusion})).toThrow('signature family kills exclusions must not contain duplicates')})
  it('fails on drift, unspecified doctrine and conflicts, and is idempotent',()=>{expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:'b'.repeat(64),authoring:authoring(),manifest:manifest()})).toThrow('legacy worksheet SHA-256 does not match');const bad=manifest();bad.families[0].adjudication.proxies='unspecified';expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:bad})).toThrow('signature family kills adjudication proxies must be explicit');const first=applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:authoring(),manifest:manifest()});const second=applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:first.worksheet,manifest:manifest()});expect(second.worksheet).toEqual(first.worksheet);first.worksheet.signature_beats[0].contract!.condition='Conflict.';expect(()=>applyLegacySignatureFamilyDecisions({legacy:legacy(),legacyWorksheetSha256:SHA,authoring:first.worksheet,manifest:manifest()})).toThrow('signature beat 1 already has a conflicting contract')})
})
