#!/usr/bin/env -S npx tsx
import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { LegacyShowPackMigrationWorksheet } from '../src/lib/legacy-show-pack-audit'
import { assessLegacyShowPackAuthoringWorksheet, serializeLegacyShowPackAuthoringWorksheet, type LegacyShowPackAuthoringWorksheet } from '../src/lib/legacy-show-pack-authoring'
import { applyLegacySignatureFamilyDecisions, type LegacySignatureFamilyDecisionManifest } from '../src/lib/legacy-signature-family-authoring'
import { assertOutputDoesNotAliasSource, writeUtf8FileSafely } from './lib/safe-write.mts'
interface O{legacy:string;authoring:string;decisions:string;output?:string;force:boolean;inPlace:boolean}
function parse(args:string[]):O{const o:O={legacy:'show-packs/research/hotd-s3-finale-legacy-worksheet.json',authoring:'show-packs/research/hotd-s3-finale-authoring.json',decisions:'',force:false,inPlace:false};for(let i=0;i<args.length;i+=1){const a=args[i];if(a==='--legacy')o.legacy=args[++i]??'';else if(a==='--authoring')o.authoring=args[++i]??'';else if(a==='--decisions')o.decisions=args[++i]??'';else if(a==='--output')o.output=args[++i]??'';else if(a==='--force')o.force=true;else if(a==='--in-place')o.inPlace=true;else throw new Error(`unknown argument ${a}`)}if(!o.decisions)throw new Error('--decisions is required');if(o.force&&!o.output)throw new Error('--force requires --output');if(o.inPlace&&(o.output||o.force))throw new Error('--in-place cannot be combined with --output or --force');return o}
function file(p:string,l:string){const r=resolve(p);if(!existsSync(r))throw new Error(`${l} does not exist: ${r}`);return r}function read(p:string,l:string){const raw=readFileSync(p,'utf8');try{return{raw,value:JSON.parse(raw)}}catch{throw new Error(`${l} is not valid JSON`)}}function sha(v:string){return createHash('sha256').update(v).digest('hex')}
function main(){const o=parse(process.argv.slice(2)),lp=file(o.legacy,'legacy worksheet'),ap=file(o.authoring,'authoring worksheet'),dp=file(o.decisions,'family decisions'),out=o.inPlace?ap:o.output?resolve(o.output):undefined,inputs=[{label:'legacy worksheet',path:lp},{label:'authoring worksheet',path:ap},{label:'family decisions',path:dp}];if(out){assertOutputDoesNotAliasSource(out,o.inPlace?inputs.filter(x=>x.path!==ap):inputs);if(!o.inPlace&&existsSync(out)&&!o.force)throw new Error(`output already exists: ${out}; pass --force`)}const li=read(lp,'legacy worksheet'),ai=read(ap,'authoring worksheet'),di=read(dp,'family decisions'),ls=sha(li.raw);console.log('[legacy-signature-family] target=local-filesystem');console.log(`[legacy-signature-family] mode=${o.inPlace?'write-in-place':out?'write':'dry-run'}`);const result=applyLegacySignatureFamilyDecisions({legacy:li.value as LegacyShowPackMigrationWorksheet,legacyWorksheetSha256:ls,authoring:ai.value as LegacyShowPackAuthoringWorksheet,manifest:di.value as LegacySignatureFamilyDecisionManifest}),status=assessLegacyShowPackAuthoringWorksheet(li.value as LegacyShowPackMigrationWorksheet,ls,result.worksheet);if(status.issues.length)throw new Error(`authoring status has issues: ${status.issues[0]}`);const bytes=serializeLegacyShowPackAuthoringWorksheet(result.worksheet);console.log(`[legacy-signature-family] batch=${(di.value as LegacySignatureFamilyDecisionManifest).batch_id}`);console.log(`[legacy-signature-family] applied=${result.applied_beat_ids.length}`);console.log(`[legacy-signature-family] contracts=${status.lanes.signature_beat_contract.filled}/${status.lanes.signature_beat_contract.total}`);console.log(`[legacy-signature-family] bytes=${Buffer.byteLength(bytes)} sha256=${sha(bytes)}`);if(!out){console.log('[legacy-signature-family] no file written');return}writeUtf8FileSafely(out,bytes,o.force||o.inPlace);console.log(`[legacy-signature-family] wrote=${out}`)}try{main()}catch(error){console.error(`[legacy-signature-family] ERROR: ${error instanceof Error?error.message:String(error)}`);process.exit(1)}
