#!/usr/bin/env python3
"""Generate the signature-beats seed migration from the v4 content JSON.

Deterministic content transform — no LLM in the loop. Reads
hotd_s3_finale_signature_beats_v4_variety_pass.json and emits INSERTs against
the signature_beats table (created empty by 20260809210000_signature_beats.sql)
plus the grouping corrections the content pass recommended.

Entity references use name+type subselects rather than hardcoded UUIDs so the
seed survives a re-run of the base HotD seed with fresh ids.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "hotd_s3_finale_signature_beats_v4_variety_pass.json"
OUT = ROOT / "supabase" / "migrations" / "20260809230000_seed_signature_beats.sql"

d = json.loads(SRC.read_text())


def q(s: str) -> str:
    """SQL-quote a string literal."""
    return "'" + s.replace("'", "''") + "'"


def ent(name: str, etype: str) -> str:
    return f"(SELECT id FROM draft_entities WHERE name = {q(name)} AND type = {q(etype)})"


lines: list[str] = []
warn = 0

lines.append("-- ============================================================================")
lines.append("-- Signature beats CONTENT — generated by scripts/generate-beats-seed.py")
lines.append("-- Source: hotd_s3_finale_signature_beats_v4_variety_pass.json (v4 variety pass)")
lines.append("--")
lines.append("-- Characters: choose-3-of-N activation model (activation plumbing in")
lines.append("-- 20260809240000). Dragons: all beats auto-active. Collision beats: one row")
lines.append("-- with partner_entity_id set; both drafters score the same points at award.")
lines.append("-- ============================================================================")
lines.append("")
lines.append("BEGIN;")
lines.append("")
lines.append("-- Idempotent: wipe and re-seed content (activations cascade).")
lines.append("DELETE FROM signature_beats;")
lines.append("")

# ── Character beats ──────────────────────────────────────────────────────────
lines.append("-- ── Character beats (choose 3 to activate) ─────────────────────────────────")
lines.append("INSERT INTO signature_beats (entity_id, name, trigger_text, odds, points, pitch) VALUES")
rows = []
n_char_beats = 0
for c in d["characters"]:
    for b in c["signature_beats"]:
        if len(b["name"]) > 22:
            print(f"WARN: beat name >22 chars: {b['name']!r} ({c['name']})", file=sys.stderr)
            warn += 1
        rows.append(
            f"  ({ent(c['name'], 'person')}, {q(b['name'])}, {q(b['trigger'])}, "
            f"{q(b['odds'])}, {b['points']}, {q(b['pitch'])})"
        )
        n_char_beats += 1
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Dragon beats (auto-active) ───────────────────────────────────────────────
lines.append("-- ── Dragon beats (auto-active, 1x multiplier via type='film') ───────────────")
lines.append("INSERT INTO signature_beats (entity_id, name, trigger_text, odds, points, pitch) VALUES")
rows = []
n_dragon_beats = 0
for dr in d["dragons"]:
    for b in dr["signature_beats"]:
        rows.append(
            f"  ({ent(dr['name'], 'film')}, {q(b['name'])}, {q(b['trigger'])}, "
            f"{q(b['odds'])}, {b['points']}, {q(b['pitch'])})"
        )
        n_dragon_beats += 1
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Collision beats ──────────────────────────────────────────────────────────
lines.append("-- ── Collision beats (always active; both drafters score points) ─────────────")
lines.append("INSERT INTO signature_beats (entity_id, partner_entity_id, name, trigger_text, odds, points, pitch) VALUES")
rows = []
for cb in d["collision_beats"]:
    a, b_char = cb["characters"]
    pts = cb["points_split"][a]
    if cb["points_split"][a] != cb["points_split"][b_char]:
        print(f"WARN: uneven split on {cb['name']}", file=sys.stderr)
        warn += 1
    rows.append(
        f"  ({ent(a, 'person')}, {ent(b_char, 'person')}, {q(cb['name'])}, "
        f"{q(cb['trigger'])}, {q(cb['odds'])}, {pts}, {q(cb['pitch'])})"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

# ── Grouping corrections (from grouping_sanity_check) ────────────────────────
lines.append("-- ── Grouping corrections recommended by the content pass ────────────────────")
moves = [(m["character"], m["to"]) for m in d["grouping_sanity_check"]["minimal_changes_if_ui_categories_must_stay"]]
renames = [(r["from"], r["to"]) for r in d["grouping_sanity_check"]["rename_recommendations"]]
for name, to in moves:
    lines.append(f"UPDATE nominees       SET film_name = {q(to)} WHERE name = {q(name)} AND type = 'person';")
    lines.append(f"UPDATE draft_entities SET film_name = {q(to)} WHERE name = {q(name)} AND type = 'person';")
for old, new in renames:
    lines.append(f"UPDATE nominees       SET film_name = {q(new)} WHERE film_name = {q(old)};")
    lines.append(f"UPDATE draft_entities SET film_name = {q(new)} WHERE film_name = {q(old)};")
lines.append("")
lines.append("COMMIT;")
lines.append("")
lines.append("-- ── Sanity ──────────────────────────────────────────────────────────────────")
lines.append(f"-- SELECT count(*) FROM signature_beats;                          -- expect {n_char_beats + n_dragon_beats + len(d['collision_beats'])}")
lines.append(f"-- SELECT count(*) FROM signature_beats WHERE partner_entity_id IS NOT NULL;  -- expect {len(d['collision_beats'])}")
lines.append("-- SELECT count(*) FROM signature_beats WHERE entity_id IS NULL;  -- expect 0 (name subselect missed = bug)")

OUT.write_text("\n".join(lines))
print(f"Wrote {OUT.relative_to(ROOT)}")
print(f"  character beats: {n_char_beats} across {len(d['characters'])} characters")
print(f"  dragon beats:    {n_dragon_beats} across {len(d['dragons'])} dragons")
print(f"  collision beats: {len(d['collision_beats'])}")
print(f"  warnings:        {warn}")

# Per-character audit against the JSON's own balance tables
audit = {a["character"]: a for a in d.get("balance_audit_v4", [])}
for c in d["characters"]:
    a = audit.get(c["name"])
    if a and a["candidate_count"] != len(c["signature_beats"]):
        print(f"WARN: {c['name']} audit says {a['candidate_count']} candidates, JSON has {len(c['signature_beats'])}", file=sys.stderr)
