/**
 * Reconstructs the live schema as a baseline migration.
 *
 * WHY THIS EXISTS
 * The repository could not rebuild its own database. The oldest migration
 * ALTERs `rooms`, and nothing in the repo ever creates it — the original schema
 * was applied by hand in the SQL editor and never checked in. So
 * `supabase db reset` failed on statement one, which meant no local stack, no
 * safe place to test a migration, and no way to stand the app up from source.
 *
 * pg_dump is the right tool for this and needs the database password. This
 * takes the other road: the Supabase Management API runs SQL with the CLI's
 * access token, so the schema can be read without a database credential.
 *
 * It is not a general-purpose pg_dump. It emits what this app actually depends
 * on, and it leans on Postgres's own pg_get_*def functions wherever they exist
 * (constraints, indexes, functions, triggers, views) so most of the output is
 * generated by the server rather than assembled here. The parts assembled here
 * — column lists, policies, grants — are verified afterwards by
 * `scripts/schema-diff.mts`, which fingerprints local and remote and compares.
 *
 *   npx tsx scripts/schema-baseline.mts > supabase/migrations/00000000000000_baseline.sql
 */

import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const ref = readFileSync(new URL('../supabase/.temp/project-ref', import.meta.url), 'utf8').trim()

const token =
  process.env.SUPABASE_ACCESS_TOKEN ??
  execFileSync('security', ['find-generic-password', '-s', 'Supabase CLI', '-w'], {
    encoding: 'utf8',
  }).trim()

async function q<T = Record<string, unknown>>(sql: string): Promise<T[]> {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`, {
    method: 'POST',
    headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' },
    body: JSON.stringify({ query: sql }),
  })
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`)
  return (await res.json()) as T[]
}

const out: string[] = []
const say = (s = '') => out.push(s)
const section = (title: string) => {
  say()
  say(`-- ${'─'.repeat(74)}`)
  say(`-- ${title}`)
  say(`-- ${'─'.repeat(74)}`)
  say()
}

const ident = (name: string) => (/^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name}"`)

say('-- Baseline schema, reconstructed from the live project.')
say('-- Generated by scripts/schema-baseline.mts — do not hand-edit; regenerate.')
say('-- Everything after this file in supabase/migrations/ is an increment on top.')

// ── Extensions ────────────────────────────────────────────────────────────────
const extensions = await q<{ extname: string; schema: string }>(`
  select extname, extnamespace::regnamespace::text as schema
  from pg_extension where extname not in ('plpgsql')
  order by extname
`)
if (extensions.length) {
  section('Extensions')
  for (const e of extensions) {
    say(`create extension if not exists ${ident(e.extname)} with schema ${ident(e.schema)};`)
  }
}

// ── Types ─────────────────────────────────────────────────────────────────────
// Enums must exist before the tables whose columns are declared with them.
// Postgres quotes the labels: the Management API marshals arrays inconsistently,
// and string_agg + quote_literal sidesteps the question entirely.
const enums = await q<{ typname: string; labels: string }>(`
  select t.typname,
         string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) as labels
  from pg_type t
  join pg_enum e      on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
  group by t.typname order by t.typname
`)
if (enums.length) {
  section(`Enum types (${enums.length})`)
  for (const e of enums) {
    // create type has no IF NOT EXISTS, so guard it for reruns.
    say(
      `do $$ begin create type public.${ident(e.typname)} as enum (${e.labels}); ` +
        `exception when duplicate_object then null; end $$;`,
    )
  }
}

const domains = await q<{ domain_name: string; data_type: string; check_clause: string | null }>(`
  select d.typname as domain_name, format_type(d.typbasetype, d.typtypmod) as data_type,
         pg_get_constraintdef(con.oid) as check_clause
  from pg_type d
  join pg_namespace n on n.oid = d.typnamespace
  left join pg_constraint con on con.contypid = d.oid
  where n.nspname = 'public' and d.typtype = 'd'
  order by d.typname
`)
if (domains.length) {
  section(`Domains (${domains.length})`)
  for (const d of domains) {
    say(
      `do $$ begin create domain public.${ident(d.domain_name)} as ${d.data_type}` +
        `${d.check_clause ? ` ${d.check_clause}` : ''}; ` +
        `exception when duplicate_object then null; end $$;`,
    )
  }
}

// ── Sequences ─────────────────────────────────────────────────────────────────
// Emitted before tables so that nextval() defaults resolve.
const sequences = await q<{ sequencename: string; data_type: string; start_value: string; increment_by: string }>(`
  select sequencename, data_type, start_value::text, increment_by::text
  from pg_sequences where schemaname = 'public' order by sequencename
`)
if (sequences.length) {
  section('Sequences')
  for (const s of sequences) {
    say(
      `create sequence if not exists public.${ident(s.sequencename)} as ${s.data_type} ` +
        `start with ${s.start_value} increment by ${s.increment_by};`,
    )
  }
}

// ── Tables ────────────────────────────────────────────────────────────────────
interface Col {
  table_name: string
  column_name: string
  type: string
  notnull: boolean
  default_expr: string | null
  identity: string | null
}
const columns = await q<Col>(`
  select c.relname          as table_name,
         a.attname          as column_name,
         format_type(a.atttypid, a.atttypmod) as type,
         a.attnotnull       as notnull,
         pg_get_expr(d.adbin, d.adrelid)      as default_expr,
         nullif(a.attidentity, '')            as identity
  from pg_attribute a
  join pg_class c     on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
    and a.attnum > 0 and not a.attisdropped
  order by c.relname, a.attnum
`)

const byTable = new Map<string, Col[]>()
for (const col of columns) {
  if (!byTable.has(col.table_name)) byTable.set(col.table_name, [])
  byTable.get(col.table_name)!.push(col)
}

section(`Tables (${byTable.size})`)
for (const [table, cols] of byTable) {
  const lines = cols.map((c) => {
    let line = `  ${ident(c.column_name)} ${c.type}`
    if (c.identity) {
      line += ` generated ${c.identity === 'a' ? 'always' : 'by default'} as identity`
    } else if (c.default_expr) {
      line += ` default ${c.default_expr}`
    }
    if (c.notnull) line += ' not null'
    return line
  })
  say(`create table if not exists public.${ident(table)} (`)
  say(lines.join(',\n'))
  say(');')
  say()
}

// ── Constraints ───────────────────────────────────────────────────────────────
// pg_get_constraintdef gives the server's own rendering; foreign keys are held
// back to the end so referenced tables already exist.
interface Con {
  table_name: string
  conname: string
  contype: string
  def: string
}
const constraints = await q<Con>(`
  select c.relname as table_name, con.conname, con.contype::text,
         pg_get_constraintdef(con.oid) as def
  from pg_constraint con
  join pg_class c     on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and con.contype in ('p','u','c','f')
  order by c.relname, con.conname
`)

const addConstraint = (c: Con) =>
  `alter table public.${ident(c.table_name)} add constraint ${ident(c.conname)} ${c.def};`

const nonFk = constraints.filter((c) => c.contype !== 'f')
if (nonFk.length) {
  section('Primary keys, unique and check constraints')
  for (const c of nonFk) say(addConstraint(c))
}

// ── Indexes ───────────────────────────────────────────────────────────────────
const constraintIndexes = new Set(
  (
    await q<{ indexname: string }>(`
      select i.relname as indexname
      from pg_constraint con
      join pg_class i on i.oid = con.conindid
      join pg_class c on c.oid = con.conrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and con.conindid <> 0
    `)
  ).map((r) => r.indexname),
)
const indexes = (
  await q<{ indexname: string; indexdef: string }>(`
    select indexname, indexdef from pg_indexes where schemaname = 'public' order by indexname
  `)
).filter((i) => !constraintIndexes.has(i.indexname))
if (indexes.length) {
  section('Indexes')
  for (const i of indexes) say(`${i.indexdef.replace(/^CREATE INDEX /, 'create index if not exists ')};`)
}

// ── Views ─────────────────────────────────────────────────────────────────────
const views = await q<{ viewname: string; definition: string }>(`
  select viewname, pg_get_viewdef(('public.' || quote_ident(viewname))::regclass, true) as definition
  from pg_views where schemaname = 'public' order by viewname
`)
if (views.length) {
  section('Views')
  for (const v of views) say(`create or replace view public.${ident(v.viewname)} as\n${v.definition}`)
}

// ── Functions ─────────────────────────────────────────────────────────────────
const functions = await q<{ def: string }>(`
  select pg_get_functiondef(p.oid) as def
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f','p')
  order by p.proname
`)
if (functions.length) {
  section('Functions')
  for (const f of functions) {
    say(f.def.replace(/^CREATE OR REPLACE FUNCTION|^CREATE FUNCTION/, 'create or replace function'))
    say(';')
    say()
  }
}

// ── Triggers ──────────────────────────────────────────────────────────────────
const triggers = await q<{ def: string }>(`
  select pg_get_triggerdef(t.oid) as def
  from pg_trigger t
  join pg_class c     on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
  order by t.tgname
`)
if (triggers.length) {
  section('Triggers')
  for (const t of triggers) say(`${t.def};`)
}

// ── Foreign keys ──────────────────────────────────────────────────────────────
const fks = constraints.filter((c) => c.contype === 'f')
if (fks.length) {
  section('Foreign keys')
  for (const c of fks) say(addConstraint(c))
}

// ── Row Level Security ────────────────────────────────────────────────────────
// RLS is the app's entire authorization layer, so a baseline without it would
// stand up a database that is wrong in the one way that matters.
const rlsTables = await q<{ relname: string }>(`
  select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
  order by c.relname
`)
if (rlsTables.length) {
  section('Row Level Security')
  for (const t of rlsTables) {
    say(`alter table public.${ident(t.relname)} enable row level security;`)
  }
}

interface Policy {
  tablename: string
  policyname: string
  permissive: string
  roles: string
  cmd: string
  qual: string | null
  with_check: string | null
}
const policies = await q<Policy>(`
  select tablename, policyname, permissive, roles::text, cmd, qual, with_check
  from pg_policies where schemaname = 'public'
  order by tablename, policyname
`)
if (policies.length) {
  section(`Policies (${policies.length})`)
  for (const p of policies) {
    const roles = p.roles.replace(/^\{|\}$/g, '')
    let stmt = `create policy ${ident(p.policyname)} on public.${ident(p.tablename)}`
    if (p.permissive?.toLowerCase() === 'restrictive') stmt += ' as restrictive'
    stmt += ` for ${p.cmd.toLowerCase()}`
    if (roles) stmt += ` to ${roles}`
    if (p.qual) stmt += ` using (${p.qual})`
    if (p.with_check) stmt += ` with check (${p.with_check})`
    say(`${stmt};`)
  }
}

// ── Grants ────────────────────────────────────────────────────────────────────
// PostgREST connects as anon/authenticated; without these the local API answers
// "permission denied" for every request and RLS never even gets a say.
const grants = await q<{ table_name: string; grantee: string; privilege_type: string }>(`
  select table_name, grantee, privilege_type
  from information_schema.role_table_grants
  where table_schema = 'public' and grantee in ('anon','authenticated','service_role')
  order by table_name, grantee, privilege_type
`)
if (grants.length) {
  section('Grants')
  const merged = new Map<string, Set<string>>()
  for (const g of grants) {
    const key = `${g.grantee}|${g.table_name}`
    if (!merged.has(key)) merged.set(key, new Set())
    merged.get(key)!.add(g.privilege_type.toLowerCase())
  }
  for (const [key, privs] of merged) {
    const [grantee, table] = key.split('|')
    say(`grant ${[...privs].sort().join(', ')} on public.${ident(table)} to ${grantee};`)
  }
}

// ── Realtime publication ──────────────────────────────────────────────────────
// Membership here is what makes a table broadcast. A table missing from the
// publication looks fine until two phones disagree.
const published = await q<{ tablename: string }>(`
  select tablename from pg_publication_tables
  where pubname = 'supabase_realtime' and schemaname = 'public'
  order by tablename
`)
if (published.length) {
  section(`Realtime publication (${published.length} tables)`)
  for (const t of published) {
    say(
      `do $$ begin alter publication supabase_realtime add table public.${ident(t.tablename)}; ` +
        `exception when duplicate_object then null; end $$;`,
    )
  }
}

say()
process.stdout.write(out.join('\n') + '\n')
