/**
 * Generates supabase/seed.sql — the authored content a local stack needs to be
 * playable, and nothing else.
 *
 * `supabase db reset` runs seed.sql after the migrations, so this is what turns
 * an empty local schema into a database you can actually open the app against:
 * the board, the cast, the draftable entities, the bingo pool.
 *
 * WHAT IT DELIBERATELY LEAVES OUT
 * Everything the party produced. rooms, players, messages, marks, picks and
 * verdicts are real people's evening — names and 176 chat lines — and this
 * repository is public. Catalog rows are selected by the fixed legacy pack;
 * room-scoped Game Master declarations and every other show pack stay out.
 *
 *   npx tsx scripts/schema-seed.mts > supabase/seed.sql
 */

import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const LEGACY_SHOW_PACK_ID = '8f27e9a4-9f6b-4f3a-9c91-a6b862c98101'

/** In dependency order — category_nominees points at both of the tables above it. */
const CONTENT_TABLES: Array<{ table: string; where?: string }> = [
  { table: 'avatars' },
  { table: 'show_packs', where: `id = '${LEGACY_SHOW_PACK_ID}'` },
  { table: 'categories', where: `show_pack_id = '${LEGACY_SHOW_PACK_ID}'` },
  { table: 'nominees', where: `show_pack_id = '${LEGACY_SHOW_PACK_ID}'` },
  {
    table: 'category_nominees',
    where: `exists (
      select 1 from public.categories category
      where category.id = t.category_id and category.show_pack_id = '${LEGACY_SHOW_PACK_ID}'
    )`,
  },
  { table: 'draft_entities', where: `show_pack_id = '${LEGACY_SHOW_PACK_ID}'` },
  { table: 'bingo_squares', where: `show_pack_id = '${LEGACY_SHOW_PACK_ID}'` },
  { table: 'signature_beats', where: `show_pack_id = '${LEGACY_SHOW_PACK_ID}'` },
]

const ref = readFileSync(new URL('../supabase/.temp/project-ref', import.meta.url), 'utf8').trim()

function accessToken(): string {
  if (process.env.SUPABASE_ACCESS_TOKEN) return process.env.SUPABASE_ACCESS_TOKEN
  const raw = execFileSync(
    'security',
    ['find-generic-password', '-s', 'Supabase CLI', '-a', 'access-token', '-w'],
    { encoding: 'utf8' },
  ).trim()
  const prefix = 'go-keyring-base64:'
  return raw.startsWith(prefix) ? Buffer.from(raw.slice(prefix.length), 'base64').toString('utf8') : raw
}

async function q<T>(sql: string): Promise<T[]> {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`, {
    method: 'POST',
    headers: { authorization: `Bearer ${accessToken()}`, 'content-type': 'application/json' },
    body: JSON.stringify({ query: sql }),
  })
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`)
  return (await res.json()) as T[]
}

/**
 * Postgres renders and quotes every value itself, via `quote_nullable(col::text)`.
 *
 * The first version of this did the quoting in JavaScript from row_to_json, and
 * got text[] wrong: json renders an array as ["a","b"] where the array literal
 * syntax Postgres wants on the way back in is {a,b}. Rather than teach this
 * script the input syntax of every type — arrays, jsonb, timestamps, enums —
 * the server emits each value in a form it will itself accept.
 */
const identSql = (name: string) => `"${name.replace(/"/g, '""')}"`

const out: string[] = [
  '-- Local development seed: authored game content only.',
  '-- Generated by scripts/schema-seed.mts — regenerate rather than hand-editing.',
  '--',
  '-- Contains no rooms, players, messages, marks, picks or verdicts: that data is',
  '-- a real evening with real names, and this repository is public.',
  '',
  '-- The baseline migration creates the fixed legacy registry as published so',
  '-- historical room defaults remain valid. Local seeding must briefly reopen',
  '-- only that pack before immutable catalog triggers permit authored inserts.',
  `update public.show_packs`,
  `set status = 'draft', published_at = null`,
  `where id = '${LEGACY_SHOW_PACK_ID}';`,
  '',
]

for (const { table, where } of CONTENT_TABLES) {
  const columns = (
    await q<{ column_name: string }>(`
      select column_name from information_schema.columns
      where table_schema = 'public' and table_name = '${table}'
      order by ordinal_position
    `)
  ).map((c) => c.column_name)

  const valueList = columns.map((c) => `quote_nullable(t.${identSql(c)}::text)`).join(", ', ', ")
  const rows = await q<{ tuple: string }>(`
    select '(' || concat_ws('', ${valueList}) || ')' as tuple
    from public.${table} t${where ? ` where ${where}` : ''}
    order by 1
  `)

  out.push(`-- ${table} (${rows.length} rows)`)
  if (!rows.length) {
    out.push('')
    continue
  }

  out.push(`insert into public.${table} (${columns.map(identSql).join(', ')}) values`)
  out.push(rows.map((r) => `  ${r.tuple}`).join(',\n'))
  // Reruns should be harmless: db reset starts empty, but a developer may run
  // this against a stack that already has content.
  out.push('on conflict do nothing;')
  out.push('')
}

out.push(
  '-- Fail closed rather than publishing a partial local catalog.',
  'do $$',
  'begin',
  `  if not public.show_pack_is_playable('${LEGACY_SHOW_PACK_ID}'::uuid) then`,
  "    raise exception 'seeded legacy show pack is not playable' using errcode = '23514';",
  '  end if;',
  '  update public.show_packs',
  "  set status = 'published', published_at = clock_timestamp()",
  `  where id = '${LEGACY_SHOW_PACK_ID}';`,
  'end;',
  '$$;',
  '',
)

process.stdout.write(out.join('\n'))
