-- Baseline schema, reconstructed from the live project.
-- Generated by scripts/schema-baseline.mts — do not hand-edit; regenerate.
-- Everything after this file in supabase/migrations/ is an increment on top.

-- ──────────────────────────────────────────────────────────────────────────
-- Extensions
-- ──────────────────────────────────────────────────────────────────────────

create extension if not exists pg_stat_statements with schema extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists supabase_vault with schema vault;
create extension if not exists "uuid-ossp" with schema extensions;

-- ──────────────────────────────────────────────────────────────────────────
-- Enum types (3)
-- ──────────────────────────────────────────────────────────────────────────

do $$ begin create type public.bingo_mark_status as enum ('pending', 'approved', 'denied'); exception when duplicate_object then null; end $$;
do $$ begin create type public.entity_type as enum ('person', 'film'); exception when duplicate_object then null; end $$;
do $$ begin create type public.room_phase as enum ('lobby', 'pre_draft', 'draft', 'confidence', 'live', 'finished', 'hot_takes', 'morning_after'); exception when duplicate_object then null; end $$;

-- ──────────────────────────────────────────────────────────────────────────
-- Sequences
-- ──────────────────────────────────────────────────────────────────────────

create sequence if not exists public.signature_beats_id_seq as integer start with 1 increment by 1;

-- ──────────────────────────────────────────────────────────────────────────
-- Tables (17)
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.avatars (
  id text not null,
  character_name text not null,
  actor_name text not null,
  film_name text not null,
  image_happy text,
  image_sad text,
  image_shocked text,
  image_neutral text
);

create table if not exists public.beat_activations (
  room_id uuid not null,
  player_id uuid not null,
  beat_id integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.bingo_cards (
  id uuid default gen_random_uuid() not null,
  room_id uuid not null,
  player_id uuid not null,
  squares jsonb not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.bingo_marks (
  id uuid default gen_random_uuid() not null,
  card_id uuid not null,
  square_index integer not null,
  status bingo_mark_status default 'pending'::bingo_mark_status,
  marked_at timestamp with time zone default now()
);

create table if not exists public.bingo_squares (
  id integer not null,
  text text not null,
  short_text text not null,
  is_objective boolean default false,
  slug text not null,
  title text not null,
  category text,
  probability_pct integer not null,
  likelihood_tier text not null,
  win_condition text not null,
  why_it_is_fun text,
  storyline_tags text[],
  fun_type text
);

create table if not exists public.categories (
  id integer not null,
  name text not null,
  tier integer not null,
  points integer not null,
  display_order integer,
  winner_id uuid,
  announced_at timestamp with time zone
);

create table if not exists public.category_nominees (
  category_id integer not null,
  nominee_id uuid not null
);

create table if not exists public.confidence_picks (
  id uuid default gen_random_uuid() not null,
  room_id uuid not null,
  player_id uuid not null,
  category_id integer not null,
  nominee_id uuid not null,
  confidence integer not null,
  is_correct boolean,
  created_at timestamp with time zone default now()
);

create table if not exists public.draft_entities (
  id uuid default gen_random_uuid() not null,
  name text not null,
  type entity_type not null,
  nominations jsonb,
  film_name text,
  nom_count integer default 1
);

create table if not exists public.draft_picks (
  id uuid default gen_random_uuid() not null,
  room_id uuid not null,
  player_id uuid not null,
  entity_id uuid not null,
  round integer not null,
  pick_number integer not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.messages (
  id uuid default gen_random_uuid() not null,
  room_id uuid not null,
  player_id text not null,
  text text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.nominees (
  id uuid default gen_random_uuid() not null,
  name text not null,
  type entity_type not null,
  film_name text,
  image_url text
);

create table if not exists public.player_verdicts (
  room_id uuid not null,
  player_id uuid not null,
  companion_id text not null,
  title text not null,
  verdict text not null,
  created_at timestamp with time zone default now() not null,
  highlights jsonb default '[]'::jsonb not null,
  imagery jsonb default '[]'::jsonb not null
);

create table if not exists public.players (
  id uuid default gen_random_uuid() not null,
  room_id uuid not null,
  name text not null,
  avatar_id text,
  color text,
  is_host boolean default false,
  created_at timestamp with time zone default now(),
  watch_group text,
  is_remote_holder boolean default false not null,
  episode_started_at timestamp with time zone,
  team text,
  welcomed_at timestamp with time zone
);

create table if not exists public.room_winners (
  room_id uuid not null,
  category_id integer not null,
  winner_id uuid not null,
  tie_winner_id uuid
);

create table if not exists public.rooms (
  id uuid default gen_random_uuid() not null,
  code text not null,
  host_id uuid,
  phase room_phase default 'lobby'::room_phase,
  draft_order jsonb,
  current_pick integer default 0,
  created_at timestamp with time zone default now(),
  ready_players jsonb default '[]'::jsonb,
  active_spotlight_category_id integer,
  show_started boolean default false not null,
  ensemble_mode text default 'full'::text not null,
  prestige_mode text default 'full'::text not null,
  sync_position_ms integer,
  sync_posted_at timestamp with time zone,
  sync_posted_by text,
  is_paused boolean default false not null,
  pause_requested_by text,
  pause_reason text,
  paused_at_ms integer,
  resume_ready jsonb default '[]'::jsonb not null,
  point_person_ids jsonb default '[]'::jsonb not null,
  resume_at timestamp with time zone,
  episode_started_at timestamp with time zone,
  countdown_started_at timestamp with time zone
);

create table if not exists public.signature_beats (
  id integer default nextval('signature_beats_id_seq'::regclass) not null,
  entity_id uuid not null,
  name text not null,
  trigger_text text default ''::text not null,
  odds text default 'coin flip'::text not null,
  points integer not null,
  pitch text default ''::text not null,
  partner_entity_id uuid
);


-- ──────────────────────────────────────────────────────────────────────────
-- Primary keys, unique and check constraints
-- ──────────────────────────────────────────────────────────────────────────

alter table public.avatars add constraint avatars_pkey PRIMARY KEY (id);
alter table public.beat_activations add constraint beat_activations_pkey PRIMARY KEY (room_id, beat_id);
alter table public.bingo_cards add constraint bingo_cards_pkey PRIMARY KEY (id);
alter table public.bingo_cards add constraint bingo_cards_room_id_player_id_key UNIQUE (room_id, player_id);
alter table public.bingo_marks add constraint bingo_marks_card_id_square_index_key UNIQUE (card_id, square_index);
alter table public.bingo_marks add constraint bingo_marks_pkey PRIMARY KEY (id);
alter table public.bingo_marks add constraint bingo_marks_square_index_check CHECK (((square_index >= 0) AND (square_index <= 24)));
alter table public.bingo_squares add constraint bingo_squares_pkey PRIMARY KEY (id);
alter table public.bingo_squares add constraint bingo_squares_probability_check CHECK (((probability_pct >= 0) AND (probability_pct <= 100)));
alter table public.bingo_squares add constraint bingo_squares_tier_check CHECK ((likelihood_tier = ANY (ARRAY['likely'::text, 'toss_up'::text, 'long_shot'::text, 'chaos'::text])));
alter table public.categories add constraint categories_pkey PRIMARY KEY (id);
alter table public.category_nominees add constraint category_nominees_pkey PRIMARY KEY (category_id, nominee_id);
alter table public.confidence_picks add constraint confidence_picks_confidence_check CHECK (((confidence >= 1) AND (confidence <= 24)));
alter table public.confidence_picks add constraint confidence_picks_pkey PRIMARY KEY (id);
alter table public.confidence_picks add constraint confidence_picks_room_id_player_id_category_id_key UNIQUE (room_id, player_id, category_id);
alter table public.draft_entities add constraint draft_entities_pkey PRIMARY KEY (id);
alter table public.draft_picks add constraint draft_picks_pkey PRIMARY KEY (id);
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.nominees add constraint nominees_pkey PRIMARY KEY (id);
alter table public.player_verdicts add constraint player_verdicts_pkey PRIMARY KEY (room_id, player_id);
alter table public.players add constraint players_pkey PRIMARY KEY (id);
alter table public.players add constraint players_team_check CHECK ((team = ANY (ARRAY['black'::text, 'green'::text])));
alter table public.room_winners add constraint room_winners_pkey PRIMARY KEY (room_id, category_id);
alter table public.rooms add constraint rooms_code_key UNIQUE (code);
alter table public.rooms add constraint rooms_ensemble_mode_check CHECK ((ensemble_mode = ANY (ARRAY['full'::text, 'stars_and_films'::text, 'films_only'::text])));
alter table public.rooms add constraint rooms_pkey PRIMARY KEY (id);
alter table public.rooms add constraint rooms_prestige_mode_check CHECK ((prestige_mode = ANY (ARRAY['full'::text, 'main_stage'::text, 'big_night'::text])));
alter table public.signature_beats add constraint signature_beats_pkey PRIMARY KEY (id);

-- ──────────────────────────────────────────────────────────────────────────
-- Indexes
-- ──────────────────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX bingo_squares_slug_key ON public.bingo_squares USING btree (slug);

-- ──────────────────────────────────────────────────────────────────────────
-- Functions
-- ──────────────────────────────────────────────────────────────────────────

create or replace function public.mark_player_ready(p_room_id uuid, p_player_id uuid)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  update rooms
  set ready_players = coalesce(ready_players, '[]'::jsonb) || to_jsonb(p_player_id::text)
  where id = p_room_id
    and not (ready_players @> to_jsonb(p_player_id::text));
$function$

;

create or replace function public.mark_resume_ready(p_room_id uuid, p_player_id text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  UPDATE rooms
  SET resume_ready = COALESCE(resume_ready, '[]'::jsonb) || to_jsonb(p_player_id)
  WHERE id = p_room_id
    AND NOT (resume_ready @> to_jsonb(p_player_id));
$function$

;

create or replace function public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$

;

create or replace function public.set_remote_holder(p_room_id uuid, p_player_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_group TEXT;
BEGIN
  SELECT watch_group INTO v_group FROM players WHERE id = p_player_id;

  UPDATE players
  SET is_remote_holder = false
  WHERE room_id = p_room_id
    AND is_remote_holder
    AND watch_group IS NOT DISTINCT FROM v_group;

  UPDATE players
  SET is_remote_holder = true
  WHERE id = p_player_id;
END;
$function$

;

create or replace function public.start_episode_for_screen(p_room_id uuid, p_player_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_group TEXT;
BEGIN
  SELECT watch_group INTO v_group FROM players WHERE id = p_player_id;

  IF v_group IS NULL THEN
    -- Solo watcher: their own screen, nobody else on it.
    UPDATE players
    SET episode_started_at = now()
    WHERE id = p_player_id
      AND episode_started_at IS NULL;
  ELSE
    -- Everyone sharing this screen gets the same origin, including whoever is
    -- still walking back from the kitchen.
    UPDATE players
    SET episode_started_at = now()
    WHERE room_id = p_room_id
      AND watch_group = v_group
      AND episode_started_at IS NULL;
  END IF;

  UPDATE rooms
  SET show_started = true
  WHERE id = p_room_id
    AND NOT show_started;
END;
$function$

;


-- ──────────────────────────────────────────────────────────────────────────
-- Foreign keys
-- ──────────────────────────────────────────────────────────────────────────

alter table public.beat_activations add constraint beat_activations_beat_id_fkey FOREIGN KEY (beat_id) REFERENCES signature_beats(id) ON DELETE CASCADE;
alter table public.beat_activations add constraint beat_activations_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.beat_activations add constraint beat_activations_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.bingo_cards add constraint bingo_cards_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.bingo_cards add constraint bingo_cards_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.bingo_marks add constraint bingo_marks_card_id_fkey FOREIGN KEY (card_id) REFERENCES bingo_cards(id) ON DELETE CASCADE;
alter table public.categories add constraint fk_categories_winner FOREIGN KEY (winner_id) REFERENCES nominees(id);
alter table public.category_nominees add constraint category_nominees_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;
alter table public.category_nominees add constraint category_nominees_nominee_id_fkey FOREIGN KEY (nominee_id) REFERENCES nominees(id) ON DELETE CASCADE;
alter table public.confidence_picks add constraint confidence_picks_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id);
alter table public.confidence_picks add constraint confidence_picks_nominee_id_fkey FOREIGN KEY (nominee_id) REFERENCES nominees(id);
alter table public.confidence_picks add constraint confidence_picks_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.confidence_picks add constraint confidence_picks_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.draft_picks add constraint draft_picks_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES draft_entities(id);
alter table public.draft_picks add constraint draft_picks_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.draft_picks add constraint draft_picks_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.player_verdicts add constraint player_verdicts_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.player_verdicts add constraint player_verdicts_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.players add constraint players_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.room_winners add constraint room_winners_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id);
alter table public.room_winners add constraint room_winners_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE;
alter table public.room_winners add constraint room_winners_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES nominees(id);
alter table public.rooms add constraint fk_rooms_host FOREIGN KEY (host_id) REFERENCES players(id);
alter table public.rooms add constraint rooms_active_spotlight_category_id_fkey FOREIGN KEY (active_spotlight_category_id) REFERENCES categories(id);
alter table public.signature_beats add constraint signature_beats_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES draft_entities(id) ON DELETE CASCADE;
alter table public.signature_beats add constraint signature_beats_partner_entity_id_fkey FOREIGN KEY (partner_entity_id) REFERENCES draft_entities(id) ON DELETE SET NULL;

-- ──────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- ──────────────────────────────────────────────────────────────────────────

alter table public.avatars enable row level security;
alter table public.beat_activations enable row level security;
alter table public.bingo_cards enable row level security;
alter table public.bingo_marks enable row level security;
alter table public.bingo_squares enable row level security;
alter table public.categories enable row level security;
alter table public.category_nominees enable row level security;
alter table public.confidence_picks enable row level security;
alter table public.draft_entities enable row level security;
alter table public.draft_picks enable row level security;
alter table public.messages enable row level security;
alter table public.nominees enable row level security;
alter table public.player_verdicts enable row level security;
alter table public.players enable row level security;
alter table public.room_winners enable row level security;
alter table public.rooms enable row level security;
alter table public.signature_beats enable row level security;

-- ──────────────────────────────────────────────────────────────────────────
-- Policies (41)
-- ──────────────────────────────────────────────────────────────────────────

create policy avatars_select on public.avatars for select to public using (true);
create policy "anon delete activations" on public.beat_activations for delete to anon,authenticated using (true);
create policy "anon insert activations" on public.beat_activations for insert to anon,authenticated with check (true);
create policy "anon read activations" on public.beat_activations for select to anon,authenticated using (true);
create policy bingo_cards_insert on public.bingo_cards for insert to public with check (true);
create policy bingo_cards_select on public.bingo_cards for select to public using (true);
create policy bingo_marks_insert on public.bingo_marks for insert to public with check (true);
create policy bingo_marks_select on public.bingo_marks for select to public using (true);
create policy bingo_marks_update on public.bingo_marks for update to public using (true);
create policy bingo_squares_select on public.bingo_squares for select to public using (true);
create policy "anon can create events" on public.categories for insert to anon,authenticated with check (true);
create policy "anon can remove events" on public.categories for delete to anon,authenticated using (true);
create policy categories_select on public.categories for select to public using (true);
create policy categories_update on public.categories for update to public using (true);
create policy "anon can link events to nominees" on public.category_nominees for insert to anon,authenticated with check (true);
create policy "anon can unlink events" on public.category_nominees for delete to anon,authenticated using (true);
create policy category_nominees_select on public.category_nominees for select to public using (true);
create policy confidence_picks_insert on public.confidence_picks for insert to public with check (true);
create policy confidence_picks_select on public.confidence_picks for select to public using (true);
create policy confidence_picks_update on public.confidence_picks for update to public using (true);
create policy draft_entities_select on public.draft_entities for select to public using (true);
create policy draft_picks_insert on public.draft_picks for insert to public with check (true);
create policy draft_picks_select on public.draft_picks for select to public using (true);
create policy messages_insert on public.messages for insert to public with check (true);
create policy messages_select on public.messages for select to public using (true);
create policy nominees_select on public.nominees for select to public using (true);
create policy "anon can read verdicts" on public.player_verdicts for select to anon,authenticated using (true);
create policy "anon can revise verdicts" on public.player_verdicts for update to anon,authenticated using (true) with check (true);
create policy "anon can write verdicts" on public.player_verdicts for insert to anon,authenticated with check (true);
create policy players_insert on public.players for insert to public with check (true);
create policy players_select on public.players for select to public using (true);
create policy players_update on public.players for update to public using (true);
create policy "Anyone can manage room winners" on public.room_winners for all to public using (true);
create policy "Anyone can read room winners" on public.room_winners for select to public using (true);
create policy rooms_insert on public.rooms for insert to public with check (true);
create policy rooms_select on public.rooms for select to public using (true);
create policy rooms_update on public.rooms for update to public using (true);
create policy "anon delete beats" on public.signature_beats for delete to anon,authenticated using (true);
create policy "anon read beats" on public.signature_beats for select to anon,authenticated using (true);
create policy "anon seed beats" on public.signature_beats for insert to anon,authenticated with check (true);
create policy "anon update beats" on public.signature_beats for update to anon,authenticated using (true);

-- ──────────────────────────────────────────────────────────────────────────
-- Grants
-- ──────────────────────────────────────────────────────────────────────────

grant delete, insert, references, select, trigger, truncate, update on public.avatars to anon;
grant delete, insert, references, select, trigger, truncate, update on public.avatars to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.avatars to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.beat_activations to anon;
grant delete, insert, references, select, trigger, truncate, update on public.beat_activations to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.beat_activations to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_cards to anon;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_cards to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_cards to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_marks to anon;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_marks to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_marks to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_squares to anon;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_squares to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.bingo_squares to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.categories to anon;
grant delete, insert, references, select, trigger, truncate, update on public.categories to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.categories to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.category_nominees to anon;
grant delete, insert, references, select, trigger, truncate, update on public.category_nominees to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.category_nominees to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.confidence_picks to anon;
grant delete, insert, references, select, trigger, truncate, update on public.confidence_picks to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.confidence_picks to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.draft_entities to anon;
grant delete, insert, references, select, trigger, truncate, update on public.draft_entities to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.draft_entities to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.draft_picks to anon;
grant delete, insert, references, select, trigger, truncate, update on public.draft_picks to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.draft_picks to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.messages to anon;
grant delete, insert, references, select, trigger, truncate, update on public.messages to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.messages to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.nominees to anon;
grant delete, insert, references, select, trigger, truncate, update on public.nominees to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.nominees to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.player_verdicts to anon;
grant delete, insert, references, select, trigger, truncate, update on public.player_verdicts to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.player_verdicts to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.players to anon;
grant delete, insert, references, select, trigger, truncate, update on public.players to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.players to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.room_winners to anon;
grant delete, insert, references, select, trigger, truncate, update on public.room_winners to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.room_winners to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.rooms to anon;
grant delete, insert, references, select, trigger, truncate, update on public.rooms to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.rooms to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.signature_beats to anon;
grant delete, insert, references, select, trigger, truncate, update on public.signature_beats to authenticated;
grant delete, insert, references, select, trigger, truncate, update on public.signature_beats to service_role;

-- ──────────────────────────────────────────────────────────────────────────
-- Realtime publication (10 tables)
-- ──────────────────────────────────────────────────────────────────────────

do $$ begin alter publication supabase_realtime add table public.beat_activations; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.bingo_marks; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.categories; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.confidence_picks; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.draft_picks; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.player_verdicts; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.players; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.room_winners; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.rooms; exception when duplicate_object then null; end $$;

