-- The researched record is room-scoped, versioned and append-only. Applying a
-- correction inserts a new version and advances rooms.active_settlement_id;
-- the provisional live rows and earlier settlements remain intact as history.

create table if not exists public.room_settlements (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  version integer not null check (version > 0),
  manifest_hash text not null check (manifest_hash ~ '^[0-9a-f]{64}$'),
  title text not null check (length(btrim(title)) > 0),
  actor text not null check (length(btrim(actor)) > 0),
  bingo_mode text not null check (bingo_mode in ('preserve_live', 'replace')),
  supersedes_id uuid references public.room_settlements(id),
  created_at timestamptz not null default now(),
  unique (id, room_id),
  unique (room_id, version),
  unique (room_id, manifest_hash),
  foreign key (supersedes_id, room_id)
    references public.room_settlements(id, room_id)
);

create table if not exists public.room_settlement_entries (
  id integer generated by default as identity primary key,
  settlement_id uuid not null references public.room_settlements(id) on delete cascade,
  entry_key text not null check (length(btrim(entry_key)) > 0),
  name text not null check (length(btrim(name)) > 0),
  category_id integer references public.categories(id),
  outcome text not null check (outcome in ('resolved', 'void')),
  points integer not null check (points > 0),
  winner_id uuid references public.nominees(id),
  tie_winner_id uuid references public.nominees(id),
  display_order integer not null,
  occurred_at timestamptz,
  warrant jsonb not null,
  unique (settlement_id, entry_key),
  unique (settlement_id, category_id),
  check (
    (outcome = 'resolved' and winner_id is not null)
    or
    (outcome = 'void' and winner_id is null and tie_winner_id is null and category_id is not null)
  ),
  check (winner_id is null or tie_winner_id is distinct from winner_id)
);

create table if not exists public.room_settlement_bingo_marks (
  settlement_id uuid not null references public.room_settlements(id) on delete cascade,
  card_id uuid not null references public.bingo_cards(id) on delete cascade,
  square_index integer not null check (square_index between 0 and 24),
  marked_at timestamptz not null default now(),
  warrant jsonb not null,
  primary key (settlement_id, card_id, square_index)
);

alter table public.rooms
  add column if not exists active_settlement_id uuid references public.room_settlements(id);

alter table public.rooms
  add constraint rooms_active_settlement_same_room
  foreign key (active_settlement_id, id)
  references public.room_settlements(id, room_id);

alter table public.rooms
  add constraint rooms_closed_has_settlement
  check (phase <> 'closed' or active_settlement_id is not null);

-- Existing room orchestration still uses anonymous direct writes, but selecting
-- the canonical researched record is an operator-only authority boundary.
revoke update on public.rooms from anon, authenticated;
grant update (
  host_id, phase, draft_order, current_pick, ready_players,
  active_spotlight_category_id, show_started, ensemble_mode, prestige_mode,
  sync_position_ms, sync_posted_at, sync_posted_by, is_paused,
  pause_requested_by, pause_reason, paused_at_ms, resume_ready,
  point_person_ids, resume_at, episode_started_at, countdown_started_at
) on public.rooms to anon, authenticated;

create or replace function public.guard_closed_room()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if old.phase = 'closed'
     and new.phase is distinct from old.phase
     and auth.role() is distinct from 'service_role' then
    raise exception 'a closed room can only be revised by the settlement operator' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger guard_closed_room
before update on public.rooms
for each row execute function public.guard_closed_room();

alter table public.room_settlements enable row level security;
alter table public.room_settlement_entries enable row level security;
alter table public.room_settlement_bingo_marks enable row level security;

create policy "settlements are readable"
  on public.room_settlements for select to anon, authenticated using (true);
create policy "settlement entries are readable"
  on public.room_settlement_entries for select to anon, authenticated using (true);
create policy "settlement bingo marks are readable"
  on public.room_settlement_bingo_marks for select to anon, authenticated using (true);

grant select on public.room_settlements to anon, authenticated;
grant select on public.room_settlement_entries to anon, authenticated;
grant select on public.room_settlement_bingo_marks to anon, authenticated;
grant all on public.room_settlements to service_role;
grant all on public.room_settlement_entries to service_role;
grant all on public.room_settlement_bingo_marks to service_role;
grant usage, select on sequence public.room_settlement_entries_id_seq to service_role;

do $$ begin
  alter publication supabase_realtime add table public.room_settlements;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.room_settlement_entries;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.room_settlement_bingo_marks;
exception when duplicate_object then null;
end $$;

create or replace function public.settle_room(
  p_room_code text,
  p_manifest_hash text,
  p_title text,
  p_actor text,
  p_bingo_mode text,
  p_entries jsonb,
  p_bingo_marks jsonb default '[]'::jsonb
)
returns table (settlement_id uuid, settlement_version integer, applied boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_room public.rooms%rowtype;
  v_existing public.room_settlements%rowtype;
  v_settlement public.room_settlements%rowtype;
  v_version integer;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'settle_room requires the service role' using errcode = '42501';
  end if;

  select * into v_room
  from public.rooms
  where code = upper(btrim(p_room_code))
  for update;

  if not found then
    raise exception 'room % not found', upper(btrim(p_room_code));
  end if;
  if v_room.phase not in ('finished', 'closed') then
    raise exception 'room % must be finished before settlement; phase is %', v_room.code, v_room.phase;
  end if;
  if p_manifest_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'manifest hash must be 64 lowercase hexadecimal characters';
  end if;
  if length(btrim(coalesce(p_title, ''))) = 0 or length(btrim(coalesce(p_actor, ''))) = 0 then
    raise exception 'settlement title and actor are required';
  end if;
  if p_bingo_mode not in ('preserve_live', 'replace') then
    raise exception 'bingo mode must be preserve_live or replace';
  end if;
  if jsonb_typeof(p_entries) is distinct from 'array' or jsonb_typeof(p_bingo_marks) is distinct from 'array' then
    raise exception 'entries and bingo marks must be arrays';
  end if;

  select * into v_existing
  from public.room_settlements
  where room_id = v_room.id and manifest_hash = p_manifest_hash;
  if found then
    if v_room.active_settlement_id = v_existing.id then
      return query select v_existing.id, v_existing.version, false;
      return;
    end if;
    raise exception 'manifest % belongs to superseded settlement version %', p_manifest_hash, v_existing.version;
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_entries) as entry(
      entry_key text, name text, category_id integer, outcome text, points integer,
      winner_id uuid, tie_winner_id uuid, display_order integer, occurred_at timestamptz, warrant jsonb
    )
    where length(btrim(coalesce(entry_key, ''))) = 0
       or length(btrim(coalesce(name, ''))) = 0
       or outcome not in ('resolved', 'void')
       or points is null or points <= 0
       or display_order is null
       or (outcome = 'resolved' and winner_id is null)
       or (outcome = 'void' and (winner_id is not null or tie_winner_id is not null or category_id is null))
       or winner_id is not null and tie_winner_id is not distinct from winner_id
       or jsonb_typeof(warrant) is distinct from 'object'
       or warrant ->> 'verdict' is distinct from 'true'
       or jsonb_typeof(warrant -> 'sources') is distinct from 'array'
       or jsonb_array_length(warrant -> 'sources') = 0
       or exists (
         select 1 from jsonb_to_recordset(warrant -> 'sources') as source(kind text, ref text)
         where length(btrim(coalesce(kind, ''))) = 0 or length(btrim(coalesce(ref, ''))) = 0
       )
  ) then
    raise exception 'every entry needs a valid outcome, attribution, points, order and true warrant with sources';
  end if;

  if exists (
    select entry_key from jsonb_to_recordset(p_entries) as entry(entry_key text)
    group by entry_key having count(*) > 1
  ) or exists (
    select category_id from jsonb_to_recordset(p_entries) as entry(category_id integer)
    where category_id is not null group by category_id having count(*) > 1
  ) then
    raise exception 'entry keys and authored category ids must be unique within a settlement';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_entries) as entry(category_id integer, points integer)
    left join public.categories category on category.id = entry.category_id
    where entry.category_id is not null
      and (category.id is null or category.points <> entry.points)
  ) then
    raise exception 'authored settlement outcomes must reference an existing category with unchanged points';
  end if;

  if exists (
    select 1
    from (select distinct category_id from public.confidence_picks where room_id = v_room.id) pick
    left join jsonb_to_recordset(p_entries) as entry(category_id integer)
      on entry.category_id = pick.category_id
    where entry.category_id is null
  ) then
    raise exception 'every staked prediction category must have an explicit settled outcome';
  end if;

  if p_bingo_mode = 'preserve_live' and jsonb_array_length(p_bingo_marks) > 0 then
    raise exception 'preserve_live settlements cannot also replace bingo marks';
  end if;
  if p_bingo_mode = 'replace' and exists (
    select 1
    from jsonb_to_recordset(p_bingo_marks) as mark(
      card_id uuid, square_index integer, marked_at timestamptz, warrant jsonb
    )
    left join public.bingo_cards card on card.id = mark.card_id and card.room_id = v_room.id
    where card.id is null
       or square_index not between 0 and 24
       or jsonb_typeof(warrant) is distinct from 'object'
       or warrant ->> 'verdict' is distinct from 'true'
       or jsonb_typeof(warrant -> 'sources') is distinct from 'array'
       or jsonb_array_length(warrant -> 'sources') = 0
       or exists (
         select 1 from jsonb_to_recordset(warrant -> 'sources') as source(kind text, ref text)
         where length(btrim(coalesce(kind, ''))) = 0 or length(btrim(coalesce(ref, ''))) = 0
       )
  ) then
    raise exception 'replacement bingo marks need a room card, valid square and true warrant with sources';
  end if;
  if exists (
    select card_id, square_index
    from jsonb_to_recordset(p_bingo_marks) as mark(card_id uuid, square_index integer)
    group by card_id, square_index having count(*) > 1
  ) then
    raise exception 'replacement bingo marks must be unique';
  end if;

  select coalesce(max(version), 0) + 1 into v_version
  from public.room_settlements where room_id = v_room.id;

  insert into public.room_settlements (
    room_id, version, manifest_hash, title, actor, bingo_mode, supersedes_id
  ) values (
    v_room.id, v_version, p_manifest_hash, btrim(p_title), btrim(p_actor),
    p_bingo_mode, v_room.active_settlement_id
  ) returning * into v_settlement;

  insert into public.room_settlement_entries (
    settlement_id, entry_key, name, category_id, outcome, points, winner_id,
    tie_winner_id, display_order, occurred_at, warrant
  )
  select v_settlement.id, entry.entry_key, entry.name, entry.category_id,
    entry.outcome, entry.points, entry.winner_id, entry.tie_winner_id,
    entry.display_order, entry.occurred_at, entry.warrant
  from jsonb_to_recordset(p_entries) as entry(
    entry_key text, name text, category_id integer, outcome text, points integer,
    winner_id uuid, tie_winner_id uuid, display_order integer, occurred_at timestamptz, warrant jsonb
  );

  if p_bingo_mode = 'replace' then
    insert into public.room_settlement_bingo_marks (
      settlement_id, card_id, square_index, marked_at, warrant
    )
    select v_settlement.id, mark.card_id, mark.square_index,
      coalesce(mark.marked_at, v_settlement.created_at), mark.warrant
    from jsonb_to_recordset(p_bingo_marks) as mark(
      card_id uuid, square_index integer, marked_at timestamptz, warrant jsonb
    );
  end if;

  update public.rooms
  set active_settlement_id = v_settlement.id, phase = 'closed'
  where id = v_room.id;

  insert into public.messages (room_id, player_id, text)
  values (v_room.id, 'system', 'The researched record is closed: ' || v_settlement.title);

  return query select v_settlement.id, v_settlement.version, true;
end;
$$;

revoke all on function public.settle_room(text, text, text, text, text, jsonb, jsonb) from public;
revoke all on function public.settle_room(text, text, text, text, text, jsonb, jsonb) from anon, authenticated;
grant execute on function public.settle_room(text, text, text, text, text, jsonb, jsonb) to service_role;
