-- ============================================================================
-- Bingo master pool — replaces the 50 hand-written squares with the researched
-- 75-square pool for the House of the Dragon S3 finale.
--
-- GENERATED FILE. Source: src/data/bingo-master-pool.json
-- Regenerate with: node scripts/generate-bingo-migration.mjs
--
-- WHAT CHANGED AND WHY
-- The old pool was written by feel and then patched once (20260809150000) to
-- pull the near-certain squares back toward the middle. This pool replaces that
-- guesswork with per-square probability estimates, so board difficulty is a
-- computed property instead of a hope. Every square also carries a strict
-- win_condition that names what does NOT count, which is the part that actually
-- matters: every mark in this game is host-adjudicated, and arguments at 10pm
-- are what kill a bingo card.
--
-- Pool shape: 15 likely / 38 toss-up / 16 long-shot / 6 chaos, averaging
-- 45.9% per square. A generated board draws 7/9/6/2 across those tiers
-- (24 live squares plus the free centre), for an expected ~11.3 hits per board.
-- Board assembly lives in generateBingoCard() in src/lib/bingo-utils.ts.
--
-- Spoiler policy from the researcher: End of Season 3 Episode 7 only.
-- No screeners, reviews, leaks, or unaired Fire & Blood outcomes.
--
-- COLUMN MAPPING
--   short_text -> title          (grid tile label)
--   text       -> win_condition  (kept in sync so older readers stay correct)
-- The new columns carry everything the old schema had no room for.
--
-- DESTRUCTIVE: square ids are reassigned, so existing bingo_cards.squares
-- arrays would point at the wrong squares. Cards and marks are wiped. Run this
-- before the finale starts, never during.
-- ============================================================================

BEGIN;

-- ── Schema: room for the researched metadata ────────────────────────────────
ALTER TABLE bingo_squares
  ADD COLUMN IF NOT EXISTS slug            text,
  ADD COLUMN IF NOT EXISTS title           text,
  ADD COLUMN IF NOT EXISTS category        text,
  ADD COLUMN IF NOT EXISTS probability_pct integer,
  ADD COLUMN IF NOT EXISTS likelihood_tier text,
  ADD COLUMN IF NOT EXISTS win_condition   text,
  ADD COLUMN IF NOT EXISTS why_it_is_fun   text,
  ADD COLUMN IF NOT EXISTS storyline_tags  text[],
  ADD COLUMN IF NOT EXISTS fun_type        text;

-- ── Clear the old pool (marks -> cards -> squares, FK order) ────────────────
DELETE FROM bingo_marks;
DELETE FROM bingo_cards;
DELETE FROM bingo_squares;

-- ── The 75-square master pool ──────────────────────────────────────────────
INSERT INTO bingo_squares
  (id, slug, title, text, short_text, is_objective,
   category, probability_pct, likelihood_tier, win_condition, why_it_is_fun, storyline_tags, fun_type)
VALUES
  (1, 'dragon_dies', 'Dragon Dies', 'A dragon must unmistakably die during the episode or be definitively confirmed dead. A crash, disappearance, or catastrophic-looking injury does not count unless the episode establishes the death.', 'Dragon Dies', false, 'dragons', 65, 'likely', 'A dragon must unmistakably die during the episode or be definitively confirmed dead. A crash, disappearance, or catastrophic-looking injury does not count unless the episode establishes the death.', 'A huge, visually obvious payoff with real stakes; strong enough to anchor a board without being guaranteed.', ARRAY['dragons', 'combat', 'death']::text[], 'spectacle'),
  (2, 'dragon_vs_dragon', 'Dragon vs Dragon', 'Two dragons must deliberately attack one another. Roaring, posturing, chasing without contact, or simply sharing a battlefield does not count.', 'Dragon vs Dragon', false, 'dragons', 70, 'likely', 'Two dragons must deliberately attack one another. Roaring, posturing, chasing without contact, or simply sharing a battlefield does not count.', 'Easy to judge in real time and exactly the kind of finale spectacle people want.', ARRAY['dragons', 'combat']::text[], 'spectacle'),
  (3, 'rider_falls', 'Rider Falls', 'A dragonrider must involuntarily fall, be thrown, or be knocked from their dragon. A planned jump, ordinary dismount, or climbing off after landing does not count.', 'Rider Falls', false, 'dragons', 45, 'toss_up', 'A dragonrider must involuntarily fall, be thrown, or be knocked from their dragon. A planned jump, ordinary dismount, or climbing off after landing does not count.', 'A classic bingo shock square: specific, visual, and immediately yell-worthy.', ARRAY['dragons', 'riders', 'combat']::text[], 'spectacle'),
  (4, 'friendly_fire', 'Friendly Fire', 'A dragon must attack, burn, injure, or kill someone fighting on its rider''s own side. An accidental near-miss does not count unless someone or something allied is actually hit.', 'Friendly Fire', false, 'dragons', 35, 'long_shot', 'A dragon must attack, burn, injure, or kill someone fighting on its rider''s own side. An accidental near-miss does not count unless someone or something allied is actually hit.', 'Calls back to the season''s repeated theme that dragons are not perfectly controllable weapons.', ARRAY['dragons', 'control', 'callback']::text[], 'callback'),
  (5, 'dragon_says_nope', 'Dragon Says Nope', 'A dragon must visibly resist, ignore, or refuse what its rider is trying to make it do. General difficulty riding or mounting does not count unless the dragon clearly asserts its own will.', 'Dragon Says Nope', false, 'dragons', 45, 'toss_up', 'A dragon must visibly resist, ignore, or refuse what its rider is trying to make it do. General difficulty riding or mounting does not count unless the dragon clearly asserts its own will.', 'Funny because the dragons increasingly seem to have better judgment than their riders.', ARRAY['dragons', 'control']::text[], 'character-comedy'),
  (6, 'dragon_snack', 'Dragon Snack', 'A dragon must visibly bite, eat, or swallow a human, animal, or substantial piece of flesh. Burning someone does not count unless the dragon actually takes a bite.', 'Dragon Snack', false, 'dragons', 30, 'long_shot', 'A dragon must visibly bite, eat, or swallow a human, animal, or substantial piece of flesh. Burning someone does not count unless the dragon actually takes a bite.', 'Gross, unmistakable, and much more fun than a generic battle square.', ARRAY['dragons', 'gore']::text[], 'chaotic'),
  (7, 'dragon_crash', 'Dragon Crash', 'A dragon must collide hard with the ground, a building, ship, another dragon, or another major object. A rough but intentional landing does not count.', 'Dragon Crash', false, 'dragons', 40, 'toss_up', 'A dragon must collide hard with the ground, a building, ship, another dragon, or another major object. A rough but intentional landing does not count.', 'A visual stunt square that can hit during almost any dragon sequence.', ARRAY['dragons', 'combat']::text[], 'spectacle'),
  (8, 'dracarys_spoken', 'Dracarys Spoken', 'A character must audibly say “Dracarys” as a command. Dragonfire without the spoken command does not satisfy the square.', 'Dracarys Spoken', false, 'dragons', 55, 'toss_up', 'A character must audibly say “Dracarys” as a command. Dragonfire without the spoken command does not satisfy the square.', 'Simple, iconic, and satisfying to mark the instant it happens.', ARRAY['dragons', 'targaryen', 'dialogue']::text[], 'catchphrase'),
  (9, 'sunfyre_love', 'Sunfyre Love', 'Aegon and Sunfyre must share a clearly affectionate or emotionally meaningful interaction. Merely appearing together, mounting, or fighting side by side does not count without an obvious emotional beat.', 'Sunfyre Love', false, 'dragons', 50, 'toss_up', 'Aegon and Sunfyre must share a clearly affectionate or emotionally meaningful interaction. Merely appearing together, mounting, or fighting side by side does not count without an obvious emotional beat.', 'The Aegon–Sunfyre reunion was one of the most audience-loved late-season moments, so this gives viewers something to actively root for.', ARRAY['aegon', 'sunfyre', 'greens']::text[], 'audience-love'),
  (10, 'vhagar_entrance', 'Vhagar Entrance', 'Vhagar must make a substantial present-day appearance that materially changes the mood or action of a scene. A distant glimpse, memory, or prophetic vision does not count.', 'Vhagar Entrance', false, 'dragons', 50, 'toss_up', 'Vhagar must make a substantial present-day appearance that materially changes the mood or action of a scene. A distant glimpse, memory, or prophetic vision does not count.', 'Vhagar entering any scene instantly changes the threat level.', ARRAY['aemond', 'vhagar', 'greens']::text[], 'spectacle'),
  (11, 'sheepstealer_justice', 'Sheepstealer Justice', 'Something genuinely positive must happen for Sheepstealer: escape, recovery, protection, reunion, food, or survival from a fresh threat. More suffering does not count; the point is that the poor dragon gets a win.', 'Sheepstealer Justice', false, 'dragons', 45, 'toss_up', 'Something genuinely positive must happen for Sheepstealer: escape, recovery, protection, reunion, food, or survival from a fresh threat. More suffering does not count; the point is that the poor dragon gets a win.', 'Directly taps the audience''s unexpectedly protective reaction to Sheepstealer after episode 7.', ARRAY['rhaena', 'sheepstealer', 'blacks']::text[], 'audience-love'),
  (12, 'dreamfyre_appears', 'Dreamfyre Appears', 'Dreamfyre must visibly appear again, either physically or unmistakably within Helaena''s prophetic experience. A spoken reference to Dreamfyre alone does not count.', 'Dreamfyre Appears', false, 'dragons', 50, 'toss_up', 'Dreamfyre must visibly appear again, either physically or unmistakably within Helaena''s prophetic experience. A spoken reference to Dreamfyre alone does not count.', 'Fans finally got a meaningful Dreamfyre reveal in episode 7, making any follow-up instantly notable.', ARRAY['helaena', 'dreamfyre', 'visions']::text[], 'audience-love'),
  (13, 'dragon_wounded', 'Dragon Wounded', 'A dragon must receive a clearly visible new injury during the finale. Existing scars or wounds carried into the episode do not count.', 'Dragon Wounded', false, 'dragons', 55, 'toss_up', 'A dragon must receive a clearly visible new injury during the finale. Existing scars or wounds carried into the episode do not count.', 'Broad enough to be viable but still gives the board a concrete visual event.', ARRAY['dragons', 'combat', 'injury']::text[], 'spectacle'),
  (14, 'dragon_hug', 'Dragon Hug', 'A rider must have an unmistakably affectionate physical interaction with their dragon, such as embracing, nuzzling, stroking, or comforting it. Mounting or handling tack does not count.', 'Dragon Hug', false, 'dragons', 25, 'long_shot', 'A rider must have an unmistakably affectionate physical interaction with their dragon, such as embracing, nuzzling, stroking, or comforting it. Mounting or handling tack does not count.', 'A rare wholesome square in a show where almost everything else is on fire.', ARRAY['dragons', 'riders', 'bond']::text[], 'audience-love'),
  (15, 'dragon_eats_name', 'Named Dragon Snack', 'A dragon must visibly kill and eat, bite apart, or swallow a named character. Burning a named character without actually using its teeth does not count.', 'Named Dragon Snack', false, 'dragons', 12, 'chaos', 'A dragon must visibly kill and eat, bite apart, or swallow a named character. Burning a named character without actually using its teeth does not count.', 'A true chaos square: low probability, incredibly memorable, and worth screaming about.', ARRAY['dragons', 'death', 'named-character']::text[], 'chaos'),
  (16, 'rhaena_screws_up', 'Rhaena Screws Up', 'Rhaena must make an identifiable decision that clearly worsens the situation. Bad luck by itself does not count; viewers should reasonably be able to say, “Rhaena, why did you do that?”', 'Rhaena Screws Up', false, 'black_court', 55, 'toss_up', 'Rhaena must make an identifiable decision that clearly worsens the situation. Bad luck by itself does not count; viewers should reasonably be able to say, “Rhaena, why did you do that?”', 'Turns the group''s frustration with her into a recurring comedy bet instead of just complaining about the character.', ARRAY['rhaena', 'sheepstealer', 'blacks']::text[], 'audience-hate'),
  (17, 'sheepstealer_rejects', 'Sheepstealer Rejects', 'Rhaena must try to reconnect with or control Sheepstealer, and Sheepstealer must actively avoid, threaten, ignore, or reject her. Remaining separated without an attempted interaction does not count.', 'Sheepstealer Rejects', false, 'black_court', 35, 'long_shot', 'Rhaena must try to reconnect with or control Sheepstealer, and Sheepstealer must actively avoid, threaten, ignore, or reject her. Remaining separated without an attempted interaction does not count.', 'Specific payoff to the season-long question of whether Rhaena can actually control the dragon she claimed.', ARRAY['rhaena', 'sheepstealer']::text[], 'character-comedy'),
  (18, 'rhaena_gets_blamed', 'Rhaena Gets Blamed', 'Another named character must directly blame or seriously criticize Rhaena for Sheepstealer, Jace, the Gullet, or her choices this season. Rhaena blaming herself does not satisfy this square.', 'Rhaena Gets Blamed', false, 'black_court', 45, 'toss_up', 'Another named character must directly blame or seriously criticize Rhaena for Sheepstealer, Jace, the Gullet, or her choices this season. Rhaena blaming herself does not satisfy this square.', 'A satisfying callback square that requires the season''s consequences to be spoken aloud.', ARRAY['rhaena', 'jace', 'gullet', 'callback']::text[], 'audience-hate'),
  (19, 'baela_side_eye', 'Baela Side-Eye', 'Baela must visibly or verbally react to Rhaena with clear annoyance, disbelief, frustration, or judgment. The reaction should be obvious enough that it does not require frame-by-frame interpretation.', 'Baela Side-Eye', false, 'black_court', 50, 'toss_up', 'Baela must visibly or verbally react to Rhaena with clear annoyance, disbelief, frustration, or judgment. The reaction should be obvious enough that it does not require frame-by-frame interpretation.', 'Small, funny, character-specific, and easy to catch during a live watch.', ARRAY['baela', 'rhaena', 'blacks']::text[], 'character-comedy'),
  (20, 'jace_guilt', 'Jace Guilt', 'A current decision or confrontation involving Rhaena, Rhaenyra, Baela, or Daemon must be explicitly tied to Jace''s death. A casual mention of Jace without present-tense consequence does not count.', 'Jace Guilt', false, 'black_court', 55, 'toss_up', 'A current decision or confrontation involving Rhaena, Rhaenyra, Baela, or Daemon must be explicitly tied to Jace''s death. A casual mention of Jace without present-tense consequence does not count.', 'Rewards the finale for paying off one of the season''s biggest emotional losses instead of simply name-checking it.', ARRAY['jace', 'rhaena', 'rhaenyra', 'callback']::text[], 'callback'),
  (21, 'daemon_daddy', 'Daemon Daddy', 'Daemon must do something clearly motivated by protecting, comforting, or loving Baela or Rhaena as their father. Tactical cooperation does not count unless the parental motivation is explicit or unmistakable.', 'Daemon Daddy', false, 'black_court', 50, 'toss_up', 'Daemon must do something clearly motivated by protecting, comforting, or loving Baela or Rhaena as their father. Tactical cooperation does not count unless the parental motivation is explicit or unmistakable.', 'A rare warm Daemon square and a continuation of the season''s more paternal turn with Rhaena.', ARRAY['daemon', 'rhaena', 'baela']::text[], 'audience-love'),
  (22, 'daemon_defies', 'Daemon Defies', 'Daemon must deliberately disobey, circumvent, or materially contradict Rhaenyra. An argument does not count if he ultimately does exactly what she orders.', 'Daemon Defies', false, 'black_court', 55, 'toss_up', 'Daemon must deliberately disobey, circumvent, or materially contradict Rhaenyra. An argument does not count if he ultimately does exactly what she orders.', 'Their fractured trust has been one of the season''s persistent Black-side tensions.', ARRAY['daemon', 'rhaenyra', 'blacks']::text[], 'conflict'),
  (23, 'rhaenyra_dragged', 'Rhaenyra Dragged', 'A named character must directly tell Rhaenyra that one of her choices has been foolish, damaging, cruel, or politically disastrous. Polite advice or mild disagreement does not count; it has to sting.', 'Rhaenyra Dragged', false, 'black_court', 65, 'likely', 'A named character must directly tell Rhaenyra that one of her choices has been foolish, damaging, cruel, or politically disastrous. Polite advice or mild disagreement does not count; it has to sting.', 'Turns a major audience frustration with her rule into a cheerable square.', ARRAY['rhaenyra', 'kings_landing', 'blacks']::text[], 'audience-hate'),
  (24, 'sapphic_spark', 'Sapphic Spark', 'Rhaenyra and Mysaria must share an unmistakably romantic or sexual continuation of their relationship, such as a kiss, sexual contact, a clear proposition, or waking together with explicit implication. Ordinary confidante intimacy does not count.', 'Sapphic Spark', false, 'black_court', 50, 'toss_up', 'Rhaenyra and Mysaria must share an unmistakably romantic or sexual continuation of their relationship, such as a kiss, sexual contact, a clear proposition, or waking together with explicit implication. Ordinary confidante intimacy does not count.', 'A fun, fandom-aware square that gives viewers something to root for beyond military outcomes.', ARRAY['rhaenyra', 'mysaria', 'romance']::text[], 'audience-love'),
  (25, 'mysaria_roasted', 'Mysaria Roasted', 'A named character must directly challenge, expose, insult, or criticize Mysaria or her influence over Rhaenyra. Generic complaints about Rhaenyra''s government do not count.', 'Mysaria Roasted', false, 'black_court', 35, 'long_shot', 'A named character must directly challenge, expose, insult, or criticize Mysaria or her influence over Rhaenyra. Generic complaints about Rhaenyra''s government do not count.', 'A payoff square for viewers frustrated by Mysaria''s influence and screen time.', ARRAY['mysaria', 'rhaenyra', 'blacks']::text[], 'audience-hate'),
  (26, 'bastard_problem', 'Bastard Problem', 'Questions about bastardy, dragonseeds, legitimacy, or resentment of Rhaenyra''s elevation of lowborn riders must materially affect a conversation or decision. A random use of the word “bastard” as an insult does not count.', 'Bastard Problem', false, 'black_court', 45, 'toss_up', 'Questions about bastardy, dragonseeds, legitimacy, or resentment of Rhaenyra''s elevation of lowborn riders must materially affect a conversation or decision. A random use of the word “bastard” as an insult does not count.', 'Keeps one of the season''s class-and-legitimacy tensions alive without requiring a specific book outcome.', ARRAY['dragonseeds', 'rhaenyra', 'legitimacy']::text[], 'callback'),
  (27, 'broke_queen', 'Broke Queen', 'The crown''s missing money or lack of funds must create a concrete problem or constrain a decision. A generic statement that war is expensive does not count.', 'Broke Queen', false, 'black_court', 45, 'toss_up', 'The crown''s missing money or lack of funds must create a concrete problem or constrain a decision. A generic statement that war is expensive does not count.', 'A season-wide callback to the less glamorous problem Rhaenyra inherited after taking King''s Landing: ruling costs money.', ARRAY['rhaenyra', 'treasury', 'kings_landing']::text[], 'callback'),
  (28, 'rhaena_cries', 'Rhaena Cries', 'Rhaena must visibly cry or emotionally break down on screen. Looking sad, wet-eyed, or miserable without an actual breakdown does not count.', 'Rhaena Cries', false, 'black_court', 55, 'toss_up', 'Rhaena must visibly cry or emotionally break down on screen. Looking sad, wet-eyed, or miserable without an actual breakdown does not count.', 'Simple, petty, highly judgeable, and exactly the kind of square that makes a watch party laugh.', ARRAY['rhaena']::text[], 'audience-hate'),
  (29, 'rhaena_says_sorry', 'Rhaena Says Sorry', 'Rhaena must explicitly apologize to another character for Sheepstealer, Jace, the Gullet, or her actions this season. Regretful expressions or self-blame without an actual apology do not count.', 'Rhaena Says Sorry', false, 'black_court', 25, 'long_shot', 'Rhaena must explicitly apologize to another character for Sheepstealer, Jace, the Gullet, or her actions this season. Regretful expressions or self-blame without an actual apology do not count.', 'A long-shot accountability square for viewers waiting for her choices to be addressed.', ARRAY['rhaena', 'jace', 'sheepstealer']::text[], 'callback'),
  (30, 'iron_throne_bites', 'Throne Bites Back', 'The Iron Throne must visibly cut, wound, or draw blood from someone during the finale. A character merely touching, sitting on, or talking about the throne does not count.', 'Throne Bites Back', false, 'black_court', 15, 'chaos', 'The Iron Throne must visibly cut, wound, or draw blood from someone during the finale. A character merely touching, sitting on, or talking about the throne does not count.', 'A pure lore-flavored chaos square with a wonderfully objective visual trigger.', ARRAY['iron_throne', 'rhaenyra', 'kings_landing']::text[], 'chaos'),
  (31, 'aegon_sass', 'Aegon Sass', 'Aegon must deliver an unmistakably sarcastic, cutting, morbidly funny, or self-aware line. Someone else joking about Aegon does not count.', 'Aegon Sass', false, 'greens_harrenhal', 70, 'likely', 'Aegon must deliver an unmistakably sarcastic, cutting, morbidly funny, or self-aware line. Someone else joking about Aegon does not count.', 'His dark humor has become one of the most entertaining parts of his wounded road-story persona.', ARRAY['aegon', 'greens']::text[], 'audience-love'),
  (32, 'aegon_goes_king', 'Aegon Goes King', 'Aegon must actively behave like a claimant again by issuing an order, demanding allegiance, rallying support, or publicly asserting royal authority. Simply surviving with Sunfyre does not count.', 'Aegon Goes King', false, 'greens_harrenhal', 55, 'toss_up', 'Aegon must actively behave like a claimant again by issuing an order, demanding allegiance, rallying support, or publicly asserting royal authority. Simply surviving with Sunfyre does not count.', 'Tests whether the late-season Sunfyre reunion translates into actual political swagger.', ARRAY['aegon', 'sunfyre', 'greens']::text[], 'character-payoff'),
  (33, 'larys_being_larys', 'Larys Being Larys', 'Larys must manipulate, betray, blackmail, strategically lie to, or quietly use somebody. His full scheme does not have to be revealed; unmistakable Larys behavior is enough.', 'Larys Being Larys', false, 'greens_harrenhal', 65, 'likely', 'Larys must manipulate, betray, blackmail, strategically lie to, or quietly use somebody. His full scheme does not have to be revealed; unmistakable Larys behavior is enough.', 'A broad but character-specific square that feels like betting on gravity.', ARRAY['larys', 'aegon', 'greens']::text[], 'character-comedy'),
  (34, 'tyland_surprise', 'Tyland Surprise', 'Tyland must do something unexpectedly brave, competent, loyal, funny, or consequential. Routine participation beside Aegon does not count.', 'Tyland Surprise', false, 'greens_harrenhal', 45, 'toss_up', 'Tyland must do something unexpectedly brave, competent, loyal, funny, or consequential. Routine participation beside Aegon does not count.', 'Gives a supporting character a chance to become the night''s random MVP.', ARRAY['tyland', 'aegon', 'greens']::text[], 'wildcard'),
  (35, 'aemond_wakes', 'Aemond Wakes', 'Aemond must clearly regain consciousness and become mentally responsive after Alicent''s poisoning. A dream or vision featuring Aemond does not count if the real Aemond remains unconscious.', 'Aemond Wakes', false, 'greens_harrenhal', 70, 'likely', 'Aemond must clearly regain consciousness and become mentally responsive after Alicent''s poisoning. A dream or vision featuring Aemond does not count if the real Aemond remains unconscious.', 'Directly resolves the episode-7 cliffhanger without predicting what he does afterward.', ARRAY['aemond', 'alicent', 'harrenhal']::text[], 'plot-payoff'),
  (36, 'mommy_issues', 'Mommy Issues', 'Aemond must again emotionally, sexually, hallucinatorily, or psychologically fixate on Alicent. A purely strategic reference to his mother does not count unless the scene clearly carries the season''s loaded maternal obsession.', 'Mommy Issues', false, 'greens_harrenhal', 50, 'toss_up', 'Aemond must again emotionally, sexually, hallucinatorily, or psychologically fixate on Alicent. A purely strategic reference to his mother does not count unless the scene clearly carries the season''s loaded maternal obsession.', 'The most meme-ready distillation of Aemond''s increasingly bizarre season arc.', ARRAY['aemond', 'alicent', 'alys']::text[], 'character-comedy'),
  (37, 'alys_witchcraft', 'Alys Witchcraft', 'Alys must do something presented as supernatural, prophetic, impossible, or deliberately witch-like. Ordinary medicine, herb lore, or vague creepiness does not count on its own.', 'Alys Witchcraft', false, 'greens_harrenhal', 50, 'toss_up', 'Alys must do something presented as supernatural, prophetic, impossible, or deliberately witch-like. Ordinary medicine, herb lore, or vague creepiness does not count on its own.', 'Lets the Harrenhal story earn its weirdness instead of just talking mysteriously.', ARRAY['alys', 'aemond', 'harrenhal']::text[], 'weird'),
  (38, 'harrenhal_gets_weird', 'Harrenhal Gets Weird', 'A present-day Harrenhal scene must contain a vision, hallucination, supernatural event, eerie omen, or similarly inexplicable occurrence. Ordinary dialogue inside Harrenhal does not count.', 'Harrenhal Gets Weird', false, 'greens_harrenhal', 65, 'likely', 'A present-day Harrenhal scene must contain a vision, hallucination, supernatural event, eerie omen, or similarly inexplicable occurrence. Ordinary dialogue inside Harrenhal does not count.', 'An easy-to-understand running gag after two seasons of Harrenhal refusing to behave like normal real estate.', ARRAY['harrenhal', 'visions', 'alys', 'aemond']::text[], 'weird'),
  (39, 'alicent_regrets_it', 'Alicent Regrets It', 'Alicent must explicitly regret poisoning Aemond or actively attempt to reverse or mitigate what she did. Merely looking distressed or conflicted does not count.', 'Alicent Regrets It', false, 'greens_harrenhal', 35, 'long_shot', 'Alicent must explicitly regret poisoning Aemond or actively attempt to reverse or mitigate what she did. Merely looking distressed or conflicted does not count.', 'A character-payoff square built around one of the penultimate episode''s biggest moral choices.', ARRAY['alicent', 'aemond']::text[], 'character-payoff'),
  (40, 'helaena_says_what', 'Helaena Says What', 'Helaena must say something clearly prophetic, ominous, bizarre, or difficult for the other characters to understand. Ordinary dialogue about her family, captivity, or pregnancy does not count.', 'Helaena Says What', false, 'greens_harrenhal', 75, 'likely', 'Helaena must say something clearly prophetic, ominous, bizarre, or difficult for the other characters to understand. Ordinary dialogue about her family, captivity, or pregnancy does not count.', 'One of the best recurring bingo beats because her visions are both plot-relevant and inherently weird.', ARRAY['helaena', 'visions', 'dreamfyre']::text[], 'audience-love'),
  (41, 'helaena_chooses', 'Helaena Chooses', 'Helaena must make a consequential decision for herself rather than simply comply with someone else''s plan. A refusal counts if it changes what happens.', 'Helaena Chooses', false, 'greens_harrenhal', 50, 'toss_up', 'Helaena must make a consequential decision for herself rather than simply comply with someone else''s plan. A refusal counts if it changes what happens.', 'Her season arc has increasingly been about asserting agency while other people try to use her.', ARRAY['helaena', 'alicent', 'greens']::text[], 'character-payoff'),
  (42, 'protect_helaena', 'Protect Helaena', 'A named character must actively defend, rescue, hide, advocate for, or otherwise protect Helaena. Feeling sorry for her or offering comfort without action does not count.', 'Protect Helaena', false, 'greens_harrenhal', 45, 'toss_up', 'A named character must actively defend, rescue, hide, advocate for, or otherwise protect Helaena. Feeling sorry for her or offering comfort without action does not count.', 'A fandom-friendly rooting square for one of the season''s most protected-by-the-audience characters.', ARRAY['helaena', 'greens']::text[], 'audience-love'),
  (43, 'poison_works', 'Poison Works', 'Aemond must die from Alicent''s poisoning, or another character must definitively state that the poison killed him. Remaining unconscious, sick, or in danger does not count.', 'Poison Works', false, 'greens_harrenhal', 25, 'long_shot', 'Aemond must die from Alicent''s poisoning, or another character must definitively state that the poison killed him. Remaining unconscious, sick, or in danger does not count.', 'A high-stakes long shot tied directly to episode 7''s cliffhanger.', ARRAY['aemond', 'alicent', 'poison']::text[], 'plot-payoff'),
  (44, 'dreamfyre_real_ride', 'Dreamfyre Takes Flight', 'Helaena must physically ride Dreamfyre in the present timeline, not merely in a dream, prophecy, memory, or vision. Dreamfyre appearing without Helaena mounted does not count.', 'Dreamfyre Takes Flight', false, 'greens_harrenhal', 18, 'chaos', 'Helaena must physically ride Dreamfyre in the present timeline, not merely in a dream, prophecy, memory, or vision. Dreamfyre appearing without Helaena mounted does not count.', 'A deliberately hard chaos square after episode 7 teased the image in a vision.', ARRAY['helaena', 'dreamfyre', 'dragonrider']::text[], 'chaos'),
  (45, 'aemond_dies', 'Aemond Dies', 'Aemond must definitively die during the finale from any cause. Severe injury, collapse, disappearance, or an ambiguous apparent death does not count.', 'Aemond Dies', false, 'greens_harrenhal', 15, 'chaos', 'Aemond must definitively die during the finale from any cause. Severe injury, collapse, disappearance, or an ambiguous apparent death does not count.', 'A true jackpot square that makes the poison cliffhanger matter without assuming its outcome.', ARRAY['aemond', 'death']::text[], 'chaos'),
  (46, 'ormund_humbled', 'Ormund Humbled', 'Ormund must suffer a real humiliation, defeat, injury, rejection, or meaningful loss of control. Someone merely disagreeing with him is not enough.', 'Ormund Humbled', false, 'tumbleton', 50, 'toss_up', 'Ormund must suffer a real humiliation, defeat, injury, rejection, or meaningful loss of control. Someone merely disagreeing with him is not enough.', 'A pure audience-payoff square for a character people enjoy hating.', ARRAY['ormund', 'hightower', 'tumbleton']::text[], 'audience-hate'),
  (47, 'daeron_defies', 'Daeron Defies', 'Daeron must openly refuse, undermine, or counter something Ormund wants him to do. Quiet discomfort or private disagreement does not count unless Daeron acts on it.', 'Daeron Defies', false, 'tumbleton', 65, 'likely', 'Daeron must openly refuse, undermine, or counter something Ormund wants him to do. Quiet discomfort or private disagreement does not count unless Daeron acts on it.', 'The Daeron–Ormund power struggle has become one of the season''s clearest internal Green conflicts.', ARRAY['daeron', 'ormund', 'tumbleton']::text[], 'audience-love'),
  (48, 'ulf_gets_smacked', 'Ulf Gets Smacked', 'Ulf must be punched, shoved, thrown down, burned, struck, or otherwise physically punished. Verbal abuse alone does not count.', 'Ulf Gets Smacked', false, 'tumbleton', 45, 'toss_up', 'Ulf must be punched, shoved, thrown down, burned, struck, or otherwise physically punished. Verbal abuse alone does not count.', 'Simple, mean, and extremely easy to adjudicate.', ARRAY['ulf', 'dragonseeds']::text[], 'audience-hate'),
  (49, 'ulf_exposed', 'Ulf Exposed', 'Someone aligned with Rhaenyra must discover or directly witness Ulf''s secret cooperation with Ormund. Private Green-side scheming does not count until the betrayed side knows.', 'Ulf Exposed', false, 'tumbleton', 55, 'toss_up', 'Someone aligned with Rhaenyra must discover or directly witness Ulf''s secret cooperation with Ormund. Private Green-side scheming does not count until the betrayed side knows.', 'A payoff to one of episode 7''s most explicit unresolved betrayal setups.', ARRAY['ulf', 'ormund', 'rhaenyra']::text[], 'plot-payoff'),
  (50, 'hugh_chooses', 'Hugh Chooses', 'Hugh must make a clear, consequential decision about his loyalties, Kat, or his role as a dragonrider and then act on it. Hesitation, complaining, or merely receiving an offer does not count.', 'Hugh Chooses', false, 'tumbleton', 50, 'toss_up', 'Hugh must make a clear, consequential decision about his loyalties, Kat, or his role as a dragonrider and then act on it. Hesitation, complaining, or merely receiving an offer does not count.', 'Keeps Hugh suspenseful without importing any unaired book outcome.', ARRAY['hugh', 'kat', 'dragonseeds']::text[], 'plot-payoff'),
  (51, 'kat_gets_out', 'Kat Gets Out', 'Kat must escape, be rescued, or otherwise be removed from immediate danger in Tumbleton. Someone offering to help her without successfully doing so does not count.', 'Kat Gets Out', false, 'tumbleton', 30, 'long_shot', 'Kat must escape, be rescued, or otherwise be removed from immediate danger in Tumbleton. Someone offering to help her without successfully doing so does not count.', 'A smaller human-scale rooting interest amid all the dragons and armies.', ARRAY['kat', 'hugh', 'tumbleton']::text[], 'audience-love'),
  (52, 'corlys_freed', 'Corlys Freed', 'Corlys must escape, be rescued, or be intentionally released from captivity. An attempted rescue does not count unless the Sea Snake actually becomes free.', 'Corlys Freed', false, 'tumbleton', 35, 'long_shot', 'Corlys must escape, be rescued, or be intentionally released from captivity. An attempted rescue does not count unless the Sea Snake actually becomes free.', 'A clean payoff to his late-season capture and a good medium-hard square.', ARRAY['corlys', 'velaryon', 'tumbleton']::text[], 'plot-payoff'),
  (53, 'alyn_goes_rogue', 'Alyn Goes Rogue', 'Alyn must disobey orders or take an unauthorized serious risk involving Corlys, Baela, the Velaryons, or the war. Normal participation in battle does not count.', 'Alyn Goes Rogue', false, 'tumbleton', 30, 'long_shot', 'Alyn must disobey orders or take an unauthorized serious risk involving Corlys, Baela, the Velaryons, or the war. Normal participation in battle does not count.', 'Makes Corlys''s capture personal and gives Alyn a chance to drive plot instead of just react.', ARRAY['alyn', 'corlys', 'velaryon']::text[], 'character-payoff'),
  (54, 'northmen_charge', 'Northmen Charge', 'Roddy Dustin, Oscar Tully, Black Aly, or their allied northern/river forces must launch or join a meaningful attack. Merely showing the army marching, camping, or discussing battle plans does not count.', 'Northmen Charge', false, 'tumbleton', 55, 'toss_up', 'Roddy Dustin, Oscar Tully, Black Aly, or their allied northern/river forces must launch or join a meaningful attack. Merely showing the army marching, camping, or discussing battle plans does not count.', 'Extends the Butcher''s Ball ground-war momentum into a concrete, cheerable event.', ARRAY['northmen', 'riverlands', 'tumbleton']::text[], 'spectacle'),
  (55, 'criston_callback', 'Criston Callback', 'Criston''s death or the consequences of his failed campaign must meaningfully affect current dialogue or a decision. Merely listing him among casualties does not count.', 'Criston Callback', false, 'tumbleton', 30, 'long_shot', 'Criston''s death or the consequences of his failed campaign must meaningfully affect current dialogue or a decision. Merely listing him among casualties does not count.', 'A callback that asks the finale to acknowledge a major season-long character rather than repeat an old scene.', ARRAY['criston', 'greens', 'callback']::text[], 'callback'),
  (56, 'tumbleton_battle', 'Tumbleton Battle', 'A substantial organized battle must begin at or immediately around Tumbleton. A tiny skirmish does not count; armies, dragons, or clearly organized military forces must genuinely engage.', 'Tumbleton Battle', false, 'tumbleton', 65, 'likely', 'A substantial organized battle must begin at or immediately around Tumbleton. A tiny skirmish does not count; armies, dragons, or clearly organized military forces must genuinely engage.', 'One of the season''s most visibly converging military threads and a natural finale anchor.', ARRAY['tumbleton', 'battle', 'hightower']::text[], 'spectacle'),
  (57, 'hostage_threat', 'Hostage Threat', 'Someone must explicitly threaten to harm, kill, mutilate, or otherwise use a captive to force another character''s behavior. Simply mentioning that a person is imprisoned does not count.', 'Hostage Threat', false, 'tumbleton', 40, 'toss_up', 'Someone must explicitly threaten to harm, kill, mutilate, or otherwise use a captive to force another character''s behavior. Simply mentioning that a person is imprisoned does not count.', 'Corlys''s captivity creates a clean setup for this without making it inevitable.', ARRAY['corlys', 'hostage', 'tumbleton']::text[], 'conflict'),
  (58, 'corlys_loses_more', 'More Corlys Parts', 'Corlys must lose another finger, limb, eye, or other body part during the finale. Threats, off-screen torture without visible loss, or injuries that leave everything attached do not count.', 'More Corlys Parts', false, 'tumbleton', 18, 'chaos', 'Corlys must lose another finger, limb, eye, or other body part during the finale. Threats, off-screen torture without visible loss, or injuries that leave everything attached do not count.', 'A nasty little chaos square based on how badly his captivity has already gone.', ARRAY['corlys', 'gore', 'captivity']::text[], 'chaos'),
  (59, 'ulf_changes_title', 'Ulf Gets a Title', 'Ulf must be formally granted, publicly promised, or seriously claim a new noble title, lordship, castle, or landholding. Empty flattery or joking titles do not count.', 'Ulf Gets a Title', false, 'tumbleton', 40, 'toss_up', 'Ulf must be formally granted, publicly promised, or seriously claim a new noble title, lordship, castle, or landholding. Empty flattery or joking titles do not count.', 'Direct payoff to Ormund using status and social recognition to tempt him.', ARRAY['ulf', 'ormund', 'status']::text[], 'plot-payoff'),
  (60, 'daeron_tessarion_love', 'Tessarion Love', 'Daeron and Tessarion must share a clearly affectionate, protective, or emotionally meaningful interaction. Routine mounting or battle commands do not count without a visible bond.', 'Tessarion Love', false, 'tumbleton', 45, 'toss_up', 'Daeron and Tessarion must share a clearly affectionate, protective, or emotionally meaningful interaction. Routine mounting or battle commands do not count without a visible bond.', 'Mirrors the audience affection for Aegon/Sunfyre and lets Daeron''s dragon relationship get its own rooting square.', ARRAY['daeron', 'tessarion', 'dragon-bond']::text[], 'audience-love'),
  (61, 'dead_son_callback', 'Dead Son Callback', 'Jace''s death must directly motivate a present-tense decision, confrontation, threat, or emotional break. A casual mention of his name or memorial image does not count.', 'Dead Son Callback', false, 'callbacks_chaos', 55, 'toss_up', 'Jace''s death must directly motivate a present-tense decision, confrontation, threat, or emotional break. A casual mention of his name or memorial image does not count.', 'A season-wide callback that only hits if the loss still matters to what people do now.', ARRAY['jace', 'callback', 'grief']::text[], 'callback'),
  (62, 'otto_shadow', 'Otto''s Shadow', 'Otto''s execution, advice, political legacy, or absence must materially influence a current decision or confrontation. A casual historical mention does not count.', 'Otto''s Shadow', false, 'callbacks_chaos', 25, 'long_shot', 'Otto''s execution, advice, political legacy, or absence must materially influence a current decision or confrontation. A casual historical mention does not count.', 'A long-shot callback to one of the season''s early turning points.', ARRAY['otto', 'alicent', 'rhaenyra', 'callback']::text[], 'callback'),
  (63, 'decoy_trick', 'Decoy Trick', 'Someone must use a fake person, false body, staged evidence, false identity, or deliberate decoy as part of an active plan. A lie told in conversation without a physical or identity-based deception does not count.', 'Decoy Trick', false, 'callbacks_chaos', 30, 'long_shot', 'Someone must use a fake person, false body, staged evidence, false identity, or deliberate decoy as part of an active plan. A lie told in conversation without a physical or identity-based deception does not count.', 'Echoes the season''s repeated use of deception and fake-outs without requiring any one past scene to be repeated.', ARRAY['deception', 'callback']::text[], 'callback'),
  (64, 'vision_fakeout', 'Vision Fakeout', 'A scene must initially appear to be happening for real and then be revealed as a dream, hallucination, prophecy, or vision. A sequence that is obviously surreal from the first shot does not count.', 'Vision Fakeout', false, 'callbacks_chaos', 45, 'toss_up', 'A scene must initially appear to be happening for real and then be revealed as a dream, hallucination, prophecy, or vision. A sequence that is obviously surreal from the first shot does not count.', 'A perfect bingo mechanic for a season that keeps weaponizing subjective reality.', ARRAY['visions', 'harrenhal', 'helaena']::text[], 'weird'),
  (65, 'rat_cameo', 'Rat Cameo', 'A living rat must be clearly visible on screen. Dead rats, rat-shaped decorations, or dialogue about rats do not count.', 'Rat Cameo', false, 'callbacks_chaos', 10, 'chaos', 'A living rat must be clearly visible on screen. Dead rats, rat-shaped decorations, or dialogue about rats do not count.', 'Tiny, objective, ridiculous, and therefore elite bingo material.', ARRAY['rat', 'kings_landing']::text[], 'chaos'),
  (66, 'wine_suspicious', 'Wine Suspicious', 'Wine or another drink must become relevant to poisoning, deception, danger, or a consequential decision. Someone simply drinking while brooding does not count.', 'Wine Suspicious', false, 'callbacks_chaos', 40, 'toss_up', 'Wine or another drink must become relevant to poisoning, deception, danger, or a consequential decision. Someone simply drinking while brooding does not count.', 'A classic Westerosi danger signal and a playful echo of this season''s poisoning thread.', ARRAY['wine', 'poison', 'deception']::text[], 'callback'),
  (67, 'brooding_window', 'Brooding Window', 'A major character must spend several silent seconds staring dramatically through a window, over a balcony, or into the distance. Walking past a window during dialogue does not count.', 'Brooding Window', false, 'callbacks_chaos', 75, 'likely', 'A major character must spend several silent seconds staring dramatically through a window, over a balcony, or into the distance. Walking past a window during dialogue does not count.', 'The premium-HBO free-space-that-isn''t-a-free-space.', ARRAY['visual-trope', 'brooding']::text[], 'trope'),
  (68, 'head_comes_off', 'Head Comes Off', 'A human head must become fully detached from its body during the episode. Sword, axe, dragon, accident, or another gruesome method all count.', 'Head Comes Off', false, 'callbacks_chaos', 40, 'toss_up', 'A human head must become fully detached from its body during the episode. Sword, axe, dragon, accident, or another gruesome method all count.', 'Specific gore is more fun than generic ''battle happens'' predictions.', ARRAY['gore', 'death']::text[], 'chaotic'),
  (69, 'someone_burns', 'Someone Burns', 'A clearly visible person must actually catch fire. Being near dragonfire, smoke, or an explosion without visibly burning does not count.', 'Someone Burns', false, 'callbacks_chaos', 70, 'likely', 'A clearly visible person must actually catch fire. Being near dragonfire, smoke, or an explosion without visibly burning does not count.', 'Very plausible in a dragon-war finale and instantly judgeable.', ARRAY['dragonfire', 'gore', 'combat']::text[], 'spectacle'),
  (70, 'gratuitous_gore', 'Gratuitous Gore', 'The camera must linger on an unusually gruesome wound, corpse, exposed anatomy, mutilation, or dismemberment. Ordinary battle blood is not enough.', 'Gratuitous Gore', false, 'callbacks_chaos', 70, 'likely', 'The camera must linger on an unusually gruesome wound, corpse, exposed anatomy, mutilation, or dismemberment. Ordinary battle blood is not enough.', 'A classic House of the Dragon reaction square that does not depend on any one storyline.', ARRAY['gore', 'visual-trope']::text[], 'trope'),
  (71, 'sex_scene', 'Sex Scene', 'The episode must depict unmistakable sexual activity between characters. Kissing, flirtation, post-sex conversation, or sex that happens entirely off-screen does not count.', 'Sex Scene', false, 'callbacks_chaos', 30, 'long_shot', 'The episode must depict unmistakable sexual activity between characters. Kissing, flirtation, post-sex conversation, or sex that happens entirely off-screen does not count.', 'Adds a very different kind of suspense to a board otherwise full of murder and dragons.', ARRAY['sex', 'romance']::text[], 'chaotic'),
  (72, 'secret_passage', 'Secret Passage', 'Someone must discover or use a concealed door, hidden corridor, tunnel, or escape route. An ordinary dungeon corridor or back staircase does not count.', 'Secret Passage', false, 'callbacks_chaos', 25, 'long_shot', 'Someone must discover or use a concealed door, hidden corridor, tunnel, or escape route. An ordinary dungeon corridor or back staircase does not count.', 'Classic King''s Landing nonsense and a useful low-probability board differentiator.', ARRAY['escape', 'kings_landing', 'deception']::text[], 'trope'),
  (73, 'raven_ruins_everything', 'Raven Ruins Everything', 'A raven-delivered message must arrive with information that significantly worsens someone''s situation or forces a change of plan. Routine correspondence or a harmless update does not count.', 'Raven Ruins Everything', false, 'callbacks_chaos', 45, 'toss_up', 'A raven-delivered message must arrive with information that significantly worsens someone''s situation or forces a change of plan. Routine correspondence or a harmless update does not count.', 'Turns exposition into a fun event: bad news by bird.', ARRAY['raven', 'message', 'politics']::text[], 'trope'),
  (74, 'someone_kneels', 'Someone Kneels', 'Someone must deliberately kneel as an act of allegiance, surrender, petition, forgiveness, or submission. Falling because of injury, exhaustion, or poisoning does not count.', 'Someone Kneels', false, 'callbacks_chaos', 65, 'likely', 'Someone must deliberately kneel as an act of allegiance, surrender, petition, forgiveness, or submission. Falling because of injury, exhaustion, or poisoning does not count.', 'Very Westerosi, extremely visible, and usable across almost every storyline.', ARRAY['allegiance', 'politics']::text[], 'trope'),
  (75, 'named_death', 'Named Death', 'Any named character must definitively die during the episode. Background soldiers, civilians, horses, nameless guards, and ambiguous apparent deaths do not count.', 'Named Death', false, 'callbacks_chaos', 80, 'likely', 'Any named character must definitively die during the episode. Background soldiers, civilians, horses, nameless guards, and ambiguous apparent deaths do not count.', 'The broadest high-probability anchor, useful for balancing difficult boards.', ARRAY['death', 'named-character']::text[], 'anchor');

-- Keep the id sequence ahead of the seeded rows if this table uses one.
DO $$
DECLARE seq text;
BEGIN
  seq := pg_get_serial_sequence('bingo_squares', 'id');
  IF seq IS NOT NULL THEN
    PERFORM setval(seq, (SELECT max(id) FROM bingo_squares), true);
  END IF;
END $$;

-- ── Constraints — enforce the contract the generator relies on ──────────────
ALTER TABLE bingo_squares
  ALTER COLUMN slug            SET NOT NULL,
  ALTER COLUMN title           SET NOT NULL,
  ALTER COLUMN probability_pct SET NOT NULL,
  ALTER COLUMN likelihood_tier SET NOT NULL,
  ALTER COLUMN win_condition   SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS bingo_squares_slug_key ON bingo_squares (slug);

ALTER TABLE bingo_squares DROP CONSTRAINT IF EXISTS bingo_squares_tier_check;
ALTER TABLE bingo_squares ADD CONSTRAINT bingo_squares_tier_check
  CHECK (likelihood_tier IN ('likely', 'toss_up', 'long_shot', 'chaos'));

ALTER TABLE bingo_squares DROP CONSTRAINT IF EXISTS bingo_squares_probability_check;
ALTER TABLE bingo_squares ADD CONSTRAINT bingo_squares_probability_check
  CHECK (probability_pct BETWEEN 0 AND 100);

COMMIT;

-- ── Sanity checks ───────────────────────────────────────────────────────────
-- SELECT count(*) FROM bingo_squares;                                  -- expect 75
-- SELECT likelihood_tier, count(*) FROM bingo_squares GROUP BY 1;      -- expect likely 15, toss_up 38, long_shot 16, chaos 6
-- SELECT round(avg(probability_pct), 1) FROM bingo_squares;            -- expect ~45.9
